; ************************************************ 
; **         THIS FILE IS AUTOGENERATED!        ** 
; ** YOU PROBABLY REALLY DON'T WANT TO EDIT IT! ** 
; ************************************************ 
; Source: template_cmd-fade-sensor.asm
	#include "sensorcfg.h"
	#include "main.h"
	#include "protocol.h"
	#include "memoryplacement.h"

	errorlevel  -302  

	CODE

do_cmd_set_sensor_fade_speed:
	global do_cmd_set_sensor_fade_speed

	; This command takes one byte of sensor ID, in packet7,
	; and one byte of state data in packet6.The sensor will
	; respond with 0x00000000 on success, or report the
	; error in packet7 on failure.
	;
	; This command takes a byte of 'delay', which is applied
	; to an PWM LED to govern how fast it 'fades' to its set
	; point.

; SENSOR_1
#ifdef SENSOR_1_PRESENT
	; this sensor?
	movfw packet7
	xorlw 1
	btfss STATUS, Z
	goto notthissensor_1

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_1_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_1_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_1:
#endif
; SENSOR_2
#ifdef SENSOR_2_PRESENT
	; this sensor?
	movfw packet7
	xorlw 2
	btfss STATUS, Z
	goto notthissensor_2

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_2_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_2_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_2:
#endif
; SENSOR_3
#ifdef SENSOR_3_PRESENT
	; this sensor?
	movfw packet7
	xorlw 3
	btfss STATUS, Z
	goto notthissensor_3

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_3_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_3_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_3:
#endif
; SENSOR_4
#ifdef SENSOR_4_PRESENT
	; this sensor?
	movfw packet7
	xorlw 4
	btfss STATUS, Z
	goto notthissensor_4

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_4_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_4_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_4:
#endif
; SENSOR_5
#ifdef SENSOR_5_PRESENT
	; this sensor?
	movfw packet7
	xorlw 5
	btfss STATUS, Z
	goto notthissensor_5

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_5_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_5_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_5:
#endif
; SENSOR_6
#ifdef SENSOR_6_PRESENT
	; this sensor?
	movfw packet7
	xorlw 6
	btfss STATUS, Z
	goto notthissensor_6

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_6_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_6_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_6:
#endif
; SENSOR_7
#ifdef SENSOR_7_PRESENT
	; this sensor?
	movfw packet7
	xorlw 7
	btfss STATUS, Z
	goto notthissensor_7

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_7_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_7_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_7:
#endif
; SENSOR_8
#ifdef SENSOR_8_PRESENT
	; this sensor?
	movfw packet7
	xorlw 8
	btfss STATUS, Z
	goto notthissensor_8

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_8_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_8_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_8:
#endif
; SENSOR_9
#ifdef SENSOR_9_PRESENT
	; this sensor?
	movfw packet7
	xorlw 9
	btfss STATUS, Z
	goto notthissensor_9

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_9_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_9_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_9:
#endif
; SENSOR_10
#ifdef SENSOR_10_PRESENT
	; this sensor?
	movfw packet7
	xorlw 10
	btfss STATUS, Z
	goto notthissensor_10

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_10_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_10_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_10:
#endif
; SENSOR_11
#ifdef SENSOR_11_PRESENT
	; this sensor?
	movfw packet7
	xorlw 11
	btfss STATUS, Z
	goto notthissensor_11

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_11_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_11_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_11:
#endif
; SENSOR_12
#ifdef SENSOR_12_PRESENT
	; this sensor?
	movfw packet7
	xorlw 12
	btfss STATUS, Z
	goto notthissensor_12

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_12_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_12_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_12:
#endif
; SENSOR_13
#ifdef SENSOR_13_PRESENT
	; this sensor?
	movfw packet7
	xorlw 13
	btfss STATUS, Z
	goto notthissensor_13

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_13_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_13_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_13:
#endif
; SENSOR_14
#ifdef SENSOR_14_PRESENT
	; this sensor?
	movfw packet7
	xorlw 14
	btfss STATUS, Z
	goto notthissensor_14

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_14_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_14_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_14:
#endif
; SENSOR_15
#ifdef SENSOR_15_PRESENT
	; this sensor?
	movfw packet7
	xorlw 15
	btfss STATUS, Z
	goto notthissensor_15

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_15_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_15_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_15:
#endif
; SENSOR_16
#ifdef SENSOR_16_PRESENT
	; this sensor?
	movfw packet7
	xorlw 16
	btfss STATUS, Z
	goto notthissensor_16

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_16_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_16_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_16:
#endif
; SENSOR_17
#ifdef SENSOR_17_PRESENT
	; this sensor?
	movfw packet7
	xorlw 17
	btfss STATUS, Z
	goto notthissensor_17

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_17_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_17_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_17:
#endif
; SENSOR_18
#ifdef SENSOR_18_PRESENT
	; this sensor?
	movfw packet7
	xorlw 18
	btfss STATUS, Z
	goto notthissensor_18

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_18_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_18_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_18:
#endif
; SENSOR_19
#ifdef SENSOR_19_PRESENT
	; this sensor?
	movfw packet7
	xorlw 19
	btfss STATUS, Z
	goto notthissensor_19

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_19_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_19_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_19:
#endif
; SENSOR_20
#ifdef SENSOR_20_PRESENT
	; this sensor?
	movfw packet7
	xorlw 20
	btfss STATUS, Z
	goto notthissensor_20

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_20_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_20_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_20:
#endif
; SENSOR_21
#ifdef SENSOR_21_PRESENT
	; this sensor?
	movfw packet7
	xorlw 21
	btfss STATUS, Z
	goto notthissensor_21

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_21_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_21_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_21:
#endif
; SENSOR_22
#ifdef SENSOR_22_PRESENT
	; this sensor?
	movfw packet7
	xorlw 22
	btfss STATUS, Z
	goto notthissensor_22

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_22_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_22_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_22:
#endif
; SENSOR_23
#ifdef SENSOR_23_PRESENT
	; this sensor?
	movfw packet7
	xorlw 23
	btfss STATUS, Z
	goto notthissensor_23

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_23_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_23_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_23:
#endif
; SENSOR_24
#ifdef SENSOR_24_PRESENT
	; this sensor?
	movfw packet7
	xorlw 24
	btfss STATUS, Z
	goto notthissensor_24

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_24_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_24_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_24:
#endif
; SENSOR_25
#ifdef SENSOR_25_PRESENT
	; this sensor?
	movfw packet7
	xorlw 25
	btfss STATUS, Z
	goto notthissensor_25

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_25_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_25_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_25:
#endif
; SENSOR_26
#ifdef SENSOR_26_PRESENT
	; this sensor?
	movfw packet7
	xorlw 26
	btfss STATUS, Z
	goto notthissensor_26

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_26_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_26_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_26:
#endif
; SENSOR_27
#ifdef SENSOR_27_PRESENT
	; this sensor?
	movfw packet7
	xorlw 27
	btfss STATUS, Z
	goto notthissensor_27

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_27_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_27_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_27:
#endif
; SENSOR_28
#ifdef SENSOR_28_PRESENT
	; this sensor?
	movfw packet7
	xorlw 28
	btfss STATUS, Z
	goto notthissensor_28

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_28_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_28_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_28:
#endif
; SENSOR_29
#ifdef SENSOR_29_PRESENT
	; this sensor?
	movfw packet7
	xorlw 29
	btfss STATUS, Z
	goto notthissensor_29

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_29_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_29_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_29:
#endif
; SENSOR_30
#ifdef SENSOR_30_PRESENT
	; this sensor?
	movfw packet7
	xorlw 30
	btfss STATUS, Z
	goto notthissensor_30

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_30_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_30_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_30:
#endif
; SENSOR_31
#ifdef SENSOR_31_PRESENT
	; this sensor?
	movfw packet7
	xorlw 31
	btfss STATUS, Z
	goto notthissensor_31

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_31_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_31_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_31:
#endif
; SENSOR_32
#ifdef SENSOR_32_PRESENT
	; this sensor?
	movfw packet7
	xorlw 32
	btfss STATUS, Z
	goto notthissensor_32

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_32_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_32_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_32:
#endif
; SENSOR_33
#ifdef SENSOR_33_PRESENT
	; this sensor?
	movfw packet7
	xorlw 33
	btfss STATUS, Z
	goto notthissensor_33

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_33_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_33_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_33:
#endif
; SENSOR_34
#ifdef SENSOR_34_PRESENT
	; this sensor?
	movfw packet7
	xorlw 34
	btfss STATUS, Z
	goto notthissensor_34

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_34_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_34_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_34:
#endif
; SENSOR_35
#ifdef SENSOR_35_PRESENT
	; this sensor?
	movfw packet7
	xorlw 35
	btfss STATUS, Z
	goto notthissensor_35

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_35_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_35_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_35:
#endif
; SENSOR_36
#ifdef SENSOR_36_PRESENT
	; this sensor?
	movfw packet7
	xorlw 36
	btfss STATUS, Z
	goto notthissensor_36

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_36_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_36_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_36:
#endif
; SENSOR_37
#ifdef SENSOR_37_PRESENT
	; this sensor?
	movfw packet7
	xorlw 37
	btfss STATUS, Z
	goto notthissensor_37

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_37_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_37_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_37:
#endif
; SENSOR_38
#ifdef SENSOR_38_PRESENT
	; this sensor?
	movfw packet7
	xorlw 38
	btfss STATUS, Z
	goto notthissensor_38

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_38_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_38_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_38:
#endif
; SENSOR_39
#ifdef SENSOR_39_PRESENT
	; this sensor?
	movfw packet7
	xorlw 39
	btfss STATUS, Z
	goto notthissensor_39

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_39_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_39_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_39:
#endif
; SENSOR_40
#ifdef SENSOR_40_PRESENT
	; this sensor?
	movfw packet7
	xorlw 40
	btfss STATUS, Z
	goto notthissensor_40

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_40_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_40_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_40:
#endif
; SENSOR_41
#ifdef SENSOR_41_PRESENT
	; this sensor?
	movfw packet7
	xorlw 41
	btfss STATUS, Z
	goto notthissensor_41

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_41_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_41_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_41:
#endif
; SENSOR_42
#ifdef SENSOR_42_PRESENT
	; this sensor?
	movfw packet7
	xorlw 42
	btfss STATUS, Z
	goto notthissensor_42

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_42_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_42_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_42:
#endif
; SENSOR_43
#ifdef SENSOR_43_PRESENT
	; this sensor?
	movfw packet7
	xorlw 43
	btfss STATUS, Z
	goto notthissensor_43

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_43_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_43_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_43:
#endif
; SENSOR_44
#ifdef SENSOR_44_PRESENT
	; this sensor?
	movfw packet7
	xorlw 44
	btfss STATUS, Z
	goto notthissensor_44

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_44_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_44_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_44:
#endif
; SENSOR_45
#ifdef SENSOR_45_PRESENT
	; this sensor?
	movfw packet7
	xorlw 45
	btfss STATUS, Z
	goto notthissensor_45

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_45_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_45_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_45:
#endif
; SENSOR_46
#ifdef SENSOR_46_PRESENT
	; this sensor?
	movfw packet7
	xorlw 46
	btfss STATUS, Z
	goto notthissensor_46

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_46_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_46_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_46:
#endif
; SENSOR_47
#ifdef SENSOR_47_PRESENT
	; this sensor?
	movfw packet7
	xorlw 47
	btfss STATUS, Z
	goto notthissensor_47

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_47_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_47_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_47:
#endif
; SENSOR_48
#ifdef SENSOR_48_PRESENT
	; this sensor?
	movfw packet7
	xorlw 48
	btfss STATUS, Z
	goto notthissensor_48

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_48_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_48_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_48:
#endif
; SENSOR_49
#ifdef SENSOR_49_PRESENT
	; this sensor?
	movfw packet7
	xorlw 49
	btfss STATUS, Z
	goto notthissensor_49

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_49_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_49_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_49:
#endif
; SENSOR_50
#ifdef SENSOR_50_PRESENT
	; this sensor?
	movfw packet7
	xorlw 50
	btfss STATUS, Z
	goto notthissensor_50

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_50_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_50_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_50:
#endif
; SENSOR_51
#ifdef SENSOR_51_PRESENT
	; this sensor?
	movfw packet7
	xorlw 51
	btfss STATUS, Z
	goto notthissensor_51

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_51_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_51_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_51:
#endif
; SENSOR_52
#ifdef SENSOR_52_PRESENT
	; this sensor?
	movfw packet7
	xorlw 52
	btfss STATUS, Z
	goto notthissensor_52

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_52_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_52_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_52:
#endif
; SENSOR_53
#ifdef SENSOR_53_PRESENT
	; this sensor?
	movfw packet7
	xorlw 53
	btfss STATUS, Z
	goto notthissensor_53

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_53_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_53_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_53:
#endif
; SENSOR_54
#ifdef SENSOR_54_PRESENT
	; this sensor?
	movfw packet7
	xorlw 54
	btfss STATUS, Z
	goto notthissensor_54

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_54_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_54_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_54:
#endif
; SENSOR_55
#ifdef SENSOR_55_PRESENT
	; this sensor?
	movfw packet7
	xorlw 55
	btfss STATUS, Z
	goto notthissensor_55

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_55_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_55_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_55:
#endif
; SENSOR_56
#ifdef SENSOR_56_PRESENT
	; this sensor?
	movfw packet7
	xorlw 56
	btfss STATUS, Z
	goto notthissensor_56

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_56_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_56_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_56:
#endif
; SENSOR_57
#ifdef SENSOR_57_PRESENT
	; this sensor?
	movfw packet7
	xorlw 57
	btfss STATUS, Z
	goto notthissensor_57

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_57_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_57_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_57:
#endif
; SENSOR_58
#ifdef SENSOR_58_PRESENT
	; this sensor?
	movfw packet7
	xorlw 58
	btfss STATUS, Z
	goto notthissensor_58

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_58_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_58_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_58:
#endif
; SENSOR_59
#ifdef SENSOR_59_PRESENT
	; this sensor?
	movfw packet7
	xorlw 59
	btfss STATUS, Z
	goto notthissensor_59

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_59_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_59_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_59:
#endif
; SENSOR_60
#ifdef SENSOR_60_PRESENT
	; this sensor?
	movfw packet7
	xorlw 60
	btfss STATUS, Z
	goto notthissensor_60

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_60_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_60_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_60:
#endif
; SENSOR_61
#ifdef SENSOR_61_PRESENT
	; this sensor?
	movfw packet7
	xorlw 61
	btfss STATUS, Z
	goto notthissensor_61

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_61_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_61_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_61:
#endif
; SENSOR_62
#ifdef SENSOR_62_PRESENT
	; this sensor?
	movfw packet7
	xorlw 62
	btfss STATUS, Z
	goto notthissensor_62

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_62_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_62_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_62:
#endif
; SENSOR_63
#ifdef SENSOR_63_PRESENT
	; this sensor?
	movfw packet7
	xorlw 63
	btfss STATUS, Z
	goto notthissensor_63

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_63_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_63_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_63:
#endif
; SENSOR_64
#ifdef SENSOR_64_PRESENT
	; this sensor?
	movfw packet7
	xorlw 64
	btfss STATUS, Z
	goto notthissensor_64

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_64_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_64_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_64:
#endif
; SENSOR_65
#ifdef SENSOR_65_PRESENT
	; this sensor?
	movfw packet7
	xorlw 65
	btfss STATUS, Z
	goto notthissensor_65

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_65_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_65_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_65:
#endif
; SENSOR_66
#ifdef SENSOR_66_PRESENT
	; this sensor?
	movfw packet7
	xorlw 66
	btfss STATUS, Z
	goto notthissensor_66

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_66_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_66_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_66:
#endif
; SENSOR_67
#ifdef SENSOR_67_PRESENT
	; this sensor?
	movfw packet7
	xorlw 67
	btfss STATUS, Z
	goto notthissensor_67

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_67_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_67_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_67:
#endif
; SENSOR_68
#ifdef SENSOR_68_PRESENT
	; this sensor?
	movfw packet7
	xorlw 68
	btfss STATUS, Z
	goto notthissensor_68

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_68_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_68_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_68:
#endif
; SENSOR_69
#ifdef SENSOR_69_PRESENT
	; this sensor?
	movfw packet7
	xorlw 69
	btfss STATUS, Z
	goto notthissensor_69

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_69_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_69_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_69:
#endif
; SENSOR_70
#ifdef SENSOR_70_PRESENT
	; this sensor?
	movfw packet7
	xorlw 70
	btfss STATUS, Z
	goto notthissensor_70

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_70_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_70_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_70:
#endif
; SENSOR_71
#ifdef SENSOR_71_PRESENT
	; this sensor?
	movfw packet7
	xorlw 71
	btfss STATUS, Z
	goto notthissensor_71

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_71_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_71_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_71:
#endif
; SENSOR_72
#ifdef SENSOR_72_PRESENT
	; this sensor?
	movfw packet7
	xorlw 72
	btfss STATUS, Z
	goto notthissensor_72

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_72_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_72_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_72:
#endif
; SENSOR_73
#ifdef SENSOR_73_PRESENT
	; this sensor?
	movfw packet7
	xorlw 73
	btfss STATUS, Z
	goto notthissensor_73

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_73_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_73_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_73:
#endif
; SENSOR_74
#ifdef SENSOR_74_PRESENT
	; this sensor?
	movfw packet7
	xorlw 74
	btfss STATUS, Z
	goto notthissensor_74

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_74_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_74_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_74:
#endif
; SENSOR_75
#ifdef SENSOR_75_PRESENT
	; this sensor?
	movfw packet7
	xorlw 75
	btfss STATUS, Z
	goto notthissensor_75

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_75_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_75_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_75:
#endif
; SENSOR_76
#ifdef SENSOR_76_PRESENT
	; this sensor?
	movfw packet7
	xorlw 76
	btfss STATUS, Z
	goto notthissensor_76

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_76_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_76_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_76:
#endif
; SENSOR_77
#ifdef SENSOR_77_PRESENT
	; this sensor?
	movfw packet7
	xorlw 77
	btfss STATUS, Z
	goto notthissensor_77

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_77_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_77_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_77:
#endif
; SENSOR_78
#ifdef SENSOR_78_PRESENT
	; this sensor?
	movfw packet7
	xorlw 78
	btfss STATUS, Z
	goto notthissensor_78

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_78_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_78_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_78:
#endif
; SENSOR_79
#ifdef SENSOR_79_PRESENT
	; this sensor?
	movfw packet7
	xorlw 79
	btfss STATUS, Z
	goto notthissensor_79

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_79_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_79_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_79:
#endif
; SENSOR_80
#ifdef SENSOR_80_PRESENT
	; this sensor?
	movfw packet7
	xorlw 80
	btfss STATUS, Z
	goto notthissensor_80

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_80_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_80_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_80:
#endif
; SENSOR_81
#ifdef SENSOR_81_PRESENT
	; this sensor?
	movfw packet7
	xorlw 81
	btfss STATUS, Z
	goto notthissensor_81

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_81_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_81_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_81:
#endif
; SENSOR_82
#ifdef SENSOR_82_PRESENT
	; this sensor?
	movfw packet7
	xorlw 82
	btfss STATUS, Z
	goto notthissensor_82

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_82_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_82_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_82:
#endif
; SENSOR_83
#ifdef SENSOR_83_PRESENT
	; this sensor?
	movfw packet7
	xorlw 83
	btfss STATUS, Z
	goto notthissensor_83

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_83_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_83_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_83:
#endif
; SENSOR_84
#ifdef SENSOR_84_PRESENT
	; this sensor?
	movfw packet7
	xorlw 84
	btfss STATUS, Z
	goto notthissensor_84

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_84_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_84_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_84:
#endif
; SENSOR_85
#ifdef SENSOR_85_PRESENT
	; this sensor?
	movfw packet7
	xorlw 85
	btfss STATUS, Z
	goto notthissensor_85

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_85_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_85_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_85:
#endif
; SENSOR_86
#ifdef SENSOR_86_PRESENT
	; this sensor?
	movfw packet7
	xorlw 86
	btfss STATUS, Z
	goto notthissensor_86

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_86_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_86_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_86:
#endif
; SENSOR_87
#ifdef SENSOR_87_PRESENT
	; this sensor?
	movfw packet7
	xorlw 87
	btfss STATUS, Z
	goto notthissensor_87

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_87_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_87_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_87:
#endif
; SENSOR_88
#ifdef SENSOR_88_PRESENT
	; this sensor?
	movfw packet7
	xorlw 88
	btfss STATUS, Z
	goto notthissensor_88

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_88_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_88_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_88:
#endif
; SENSOR_89
#ifdef SENSOR_89_PRESENT
	; this sensor?
	movfw packet7
	xorlw 89
	btfss STATUS, Z
	goto notthissensor_89

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_89_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_89_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_89:
#endif
; SENSOR_90
#ifdef SENSOR_90_PRESENT
	; this sensor?
	movfw packet7
	xorlw 90
	btfss STATUS, Z
	goto notthissensor_90

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_90_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_90_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_90:
#endif
; SENSOR_91
#ifdef SENSOR_91_PRESENT
	; this sensor?
	movfw packet7
	xorlw 91
	btfss STATUS, Z
	goto notthissensor_91

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_91_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_91_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_91:
#endif
; SENSOR_92
#ifdef SENSOR_92_PRESENT
	; this sensor?
	movfw packet7
	xorlw 92
	btfss STATUS, Z
	goto notthissensor_92

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_92_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_92_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_92:
#endif
; SENSOR_93
#ifdef SENSOR_93_PRESENT
	; this sensor?
	movfw packet7
	xorlw 93
	btfss STATUS, Z
	goto notthissensor_93

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_93_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_93_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_93:
#endif
; SENSOR_94
#ifdef SENSOR_94_PRESENT
	; this sensor?
	movfw packet7
	xorlw 94
	btfss STATUS, Z
	goto notthissensor_94

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_94_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_94_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_94:
#endif
; SENSOR_95
#ifdef SENSOR_95_PRESENT
	; this sensor?
	movfw packet7
	xorlw 95
	btfss STATUS, Z
	goto notthissensor_95

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_95_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_95_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_95:
#endif
; SENSOR_96
#ifdef SENSOR_96_PRESENT
	; this sensor?
	movfw packet7
	xorlw 96
	btfss STATUS, Z
	goto notthissensor_96

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_96_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_96_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_96:
#endif
; SENSOR_97
#ifdef SENSOR_97_PRESENT
	; this sensor?
	movfw packet7
	xorlw 97
	btfss STATUS, Z
	goto notthissensor_97

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_97_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_97_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_97:
#endif
; SENSOR_98
#ifdef SENSOR_98_PRESENT
	; this sensor?
	movfw packet7
	xorlw 98
	btfss STATUS, Z
	goto notthissensor_98

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_98_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_98_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_98:
#endif
; SENSOR_99
#ifdef SENSOR_99_PRESENT
	; this sensor?
	movfw packet7
	xorlw 99
	btfss STATUS, Z
	goto notthissensor_99

	; Yup, this sensor. Save the data we're interested in.
	#if (SENSOR_ID_PWM_LED == SENSOR_99_TYPE)
		movfw packet6
		bsf STATUS, RP0 ; bank 1
		movwf SENSOR_99_PWM_SPEED
		bcf STATUS, RP0 ; bank 0
		goto returnOK
	#else 
		goto wrongType
	#endif
notthissensor_99:
#endif
	clrf packet4
	clrf packet5
	clrf packet6
	movlw ERR_SET_SENSOR_FADE_NOT_FOUND
	movwf packet7
	return

wrongType:
	clrf packet4
	clrf packet5
	clrf packet6
	movlw ERR_SET_SENSOR_FADE_WRONG_TYPE
	movwf packet7
	return

returnOK:
	clrf packet4
	clrf packet5
	clrf packet6
	movlw ERR_SENSOR_NONE
	movwf packet7
	return

	end