; ************************************************ 
; **         THIS FILE IS AUTOGENERATED!        ** 
; ** YOU PROBABLY REALLY DON'T WANT TO EDIT IT! ** 
; ************************************************ 
; Source: template_memoryplacement.h

; Stuff below here are variables used by sensors, which are
; 'placed' at compile-time in bank 1.

placeinmemory macro base
	local memptr = base



#ifdef SENSOR_1_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_1_TYPE)

SENSOR_1_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_1_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_1_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_1_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_1_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_1_TYPE)

SENSOR_1_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_1_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_2_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_2_TYPE)

SENSOR_2_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_2_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_2_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_2_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_2_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_2_TYPE)

SENSOR_2_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_2_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_3_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_3_TYPE)

SENSOR_3_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_3_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_3_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_3_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_3_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_3_TYPE)

SENSOR_3_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_3_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_4_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_4_TYPE)

SENSOR_4_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_4_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_4_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_4_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_4_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_4_TYPE)

SENSOR_4_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_4_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_5_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_5_TYPE)

SENSOR_5_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_5_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_5_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_5_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_5_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_5_TYPE)

SENSOR_5_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_5_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_6_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_6_TYPE)

SENSOR_6_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_6_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_6_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_6_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_6_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_6_TYPE)

SENSOR_6_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_6_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_7_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_7_TYPE)

SENSOR_7_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_7_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_7_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_7_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_7_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_7_TYPE)

SENSOR_7_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_7_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_8_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_8_TYPE)

SENSOR_8_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_8_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_8_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_8_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_8_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_8_TYPE)

SENSOR_8_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_8_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_9_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_9_TYPE)

SENSOR_9_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_9_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_9_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_9_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_9_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_9_TYPE)

SENSOR_9_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_9_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_10_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_10_TYPE)

SENSOR_10_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_10_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_10_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_10_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_10_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_10_TYPE)

SENSOR_10_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_10_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_11_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_11_TYPE)

SENSOR_11_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_11_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_11_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_11_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_11_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_11_TYPE)

SENSOR_11_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_11_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_12_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_12_TYPE)

SENSOR_12_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_12_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_12_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_12_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_12_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_12_TYPE)

SENSOR_12_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_12_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_13_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_13_TYPE)

SENSOR_13_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_13_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_13_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_13_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_13_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_13_TYPE)

SENSOR_13_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_13_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_14_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_14_TYPE)

SENSOR_14_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_14_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_14_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_14_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_14_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_14_TYPE)

SENSOR_14_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_14_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_15_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_15_TYPE)

SENSOR_15_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_15_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_15_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_15_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_15_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_15_TYPE)

SENSOR_15_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_15_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_16_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_16_TYPE)

SENSOR_16_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_16_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_16_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_16_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_16_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_16_TYPE)

SENSOR_16_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_16_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_17_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_17_TYPE)

SENSOR_17_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_17_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_17_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_17_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_17_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_17_TYPE)

SENSOR_17_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_17_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_18_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_18_TYPE)

SENSOR_18_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_18_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_18_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_18_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_18_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_18_TYPE)

SENSOR_18_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_18_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_19_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_19_TYPE)

SENSOR_19_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_19_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_19_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_19_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_19_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_19_TYPE)

SENSOR_19_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_19_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_20_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_20_TYPE)

SENSOR_20_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_20_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_20_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_20_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_20_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_20_TYPE)

SENSOR_20_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_20_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_21_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_21_TYPE)

SENSOR_21_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_21_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_21_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_21_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_21_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_21_TYPE)

SENSOR_21_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_21_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_22_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_22_TYPE)

SENSOR_22_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_22_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_22_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_22_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_22_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_22_TYPE)

SENSOR_22_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_22_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_23_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_23_TYPE)

SENSOR_23_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_23_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_23_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_23_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_23_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_23_TYPE)

SENSOR_23_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_23_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_24_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_24_TYPE)

SENSOR_24_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_24_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_24_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_24_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_24_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_24_TYPE)

SENSOR_24_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_24_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_25_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_25_TYPE)

SENSOR_25_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_25_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_25_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_25_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_25_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_25_TYPE)

SENSOR_25_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_25_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_26_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_26_TYPE)

SENSOR_26_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_26_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_26_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_26_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_26_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_26_TYPE)

SENSOR_26_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_26_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_27_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_27_TYPE)

SENSOR_27_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_27_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_27_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_27_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_27_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_27_TYPE)

SENSOR_27_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_27_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_28_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_28_TYPE)

SENSOR_28_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_28_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_28_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_28_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_28_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_28_TYPE)

SENSOR_28_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_28_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_29_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_29_TYPE)

SENSOR_29_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_29_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_29_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_29_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_29_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_29_TYPE)

SENSOR_29_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_29_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_30_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_30_TYPE)

SENSOR_30_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_30_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_30_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_30_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_30_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_30_TYPE)

SENSOR_30_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_30_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_31_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_31_TYPE)

SENSOR_31_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_31_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_31_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_31_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_31_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_31_TYPE)

SENSOR_31_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_31_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_32_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_32_TYPE)

SENSOR_32_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_32_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_32_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_32_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_32_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_32_TYPE)

SENSOR_32_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_32_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_33_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_33_TYPE)

SENSOR_33_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_33_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_33_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_33_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_33_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_33_TYPE)

SENSOR_33_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_33_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_34_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_34_TYPE)

SENSOR_34_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_34_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_34_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_34_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_34_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_34_TYPE)

SENSOR_34_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_34_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_35_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_35_TYPE)

SENSOR_35_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_35_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_35_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_35_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_35_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_35_TYPE)

SENSOR_35_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_35_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_36_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_36_TYPE)

SENSOR_36_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_36_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_36_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_36_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_36_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_36_TYPE)

SENSOR_36_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_36_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_37_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_37_TYPE)

SENSOR_37_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_37_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_37_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_37_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_37_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_37_TYPE)

SENSOR_37_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_37_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_38_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_38_TYPE)

SENSOR_38_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_38_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_38_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_38_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_38_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_38_TYPE)

SENSOR_38_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_38_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_39_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_39_TYPE)

SENSOR_39_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_39_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_39_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_39_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_39_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_39_TYPE)

SENSOR_39_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_39_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_40_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_40_TYPE)

SENSOR_40_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_40_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_40_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_40_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_40_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_40_TYPE)

SENSOR_40_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_40_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_41_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_41_TYPE)

SENSOR_41_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_41_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_41_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_41_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_41_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_41_TYPE)

SENSOR_41_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_41_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_42_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_42_TYPE)

SENSOR_42_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_42_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_42_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_42_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_42_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_42_TYPE)

SENSOR_42_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_42_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_43_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_43_TYPE)

SENSOR_43_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_43_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_43_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_43_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_43_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_43_TYPE)

SENSOR_43_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_43_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_44_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_44_TYPE)

SENSOR_44_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_44_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_44_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_44_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_44_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_44_TYPE)

SENSOR_44_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_44_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_45_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_45_TYPE)

SENSOR_45_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_45_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_45_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_45_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_45_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_45_TYPE)

SENSOR_45_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_45_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_46_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_46_TYPE)

SENSOR_46_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_46_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_46_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_46_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_46_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_46_TYPE)

SENSOR_46_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_46_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_47_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_47_TYPE)

SENSOR_47_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_47_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_47_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_47_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_47_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_47_TYPE)

SENSOR_47_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_47_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_48_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_48_TYPE)

SENSOR_48_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_48_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_48_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_48_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_48_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_48_TYPE)

SENSOR_48_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_48_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_49_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_49_TYPE)

SENSOR_49_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_49_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_49_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_49_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_49_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_49_TYPE)

SENSOR_49_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_49_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_50_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_50_TYPE)

SENSOR_50_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_50_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_50_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_50_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_50_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_50_TYPE)

SENSOR_50_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_50_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_51_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_51_TYPE)

SENSOR_51_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_51_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_51_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_51_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_51_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_51_TYPE)

SENSOR_51_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_51_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_52_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_52_TYPE)

SENSOR_52_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_52_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_52_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_52_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_52_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_52_TYPE)

SENSOR_52_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_52_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_53_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_53_TYPE)

SENSOR_53_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_53_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_53_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_53_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_53_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_53_TYPE)

SENSOR_53_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_53_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_54_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_54_TYPE)

SENSOR_54_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_54_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_54_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_54_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_54_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_54_TYPE)

SENSOR_54_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_54_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_55_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_55_TYPE)

SENSOR_55_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_55_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_55_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_55_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_55_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_55_TYPE)

SENSOR_55_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_55_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_56_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_56_TYPE)

SENSOR_56_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_56_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_56_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_56_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_56_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_56_TYPE)

SENSOR_56_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_56_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_57_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_57_TYPE)

SENSOR_57_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_57_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_57_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_57_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_57_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_57_TYPE)

SENSOR_57_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_57_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_58_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_58_TYPE)

SENSOR_58_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_58_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_58_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_58_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_58_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_58_TYPE)

SENSOR_58_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_58_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_59_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_59_TYPE)

SENSOR_59_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_59_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_59_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_59_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_59_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_59_TYPE)

SENSOR_59_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_59_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_60_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_60_TYPE)

SENSOR_60_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_60_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_60_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_60_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_60_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_60_TYPE)

SENSOR_60_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_60_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_61_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_61_TYPE)

SENSOR_61_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_61_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_61_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_61_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_61_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_61_TYPE)

SENSOR_61_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_61_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_62_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_62_TYPE)

SENSOR_62_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_62_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_62_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_62_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_62_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_62_TYPE)

SENSOR_62_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_62_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_63_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_63_TYPE)

SENSOR_63_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_63_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_63_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_63_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_63_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_63_TYPE)

SENSOR_63_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_63_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_64_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_64_TYPE)

SENSOR_64_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_64_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_64_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_64_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_64_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_64_TYPE)

SENSOR_64_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_64_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_65_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_65_TYPE)

SENSOR_65_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_65_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_65_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_65_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_65_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_65_TYPE)

SENSOR_65_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_65_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_66_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_66_TYPE)

SENSOR_66_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_66_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_66_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_66_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_66_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_66_TYPE)

SENSOR_66_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_66_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_67_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_67_TYPE)

SENSOR_67_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_67_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_67_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_67_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_67_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_67_TYPE)

SENSOR_67_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_67_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_68_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_68_TYPE)

SENSOR_68_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_68_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_68_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_68_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_68_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_68_TYPE)

SENSOR_68_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_68_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_69_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_69_TYPE)

SENSOR_69_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_69_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_69_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_69_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_69_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_69_TYPE)

SENSOR_69_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_69_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_70_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_70_TYPE)

SENSOR_70_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_70_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_70_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_70_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_70_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_70_TYPE)

SENSOR_70_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_70_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_71_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_71_TYPE)

SENSOR_71_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_71_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_71_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_71_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_71_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_71_TYPE)

SENSOR_71_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_71_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_72_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_72_TYPE)

SENSOR_72_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_72_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_72_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_72_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_72_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_72_TYPE)

SENSOR_72_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_72_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_73_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_73_TYPE)

SENSOR_73_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_73_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_73_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_73_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_73_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_73_TYPE)

SENSOR_73_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_73_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_74_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_74_TYPE)

SENSOR_74_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_74_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_74_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_74_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_74_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_74_TYPE)

SENSOR_74_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_74_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_75_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_75_TYPE)

SENSOR_75_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_75_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_75_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_75_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_75_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_75_TYPE)

SENSOR_75_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_75_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_76_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_76_TYPE)

SENSOR_76_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_76_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_76_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_76_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_76_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_76_TYPE)

SENSOR_76_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_76_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_77_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_77_TYPE)

SENSOR_77_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_77_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_77_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_77_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_77_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_77_TYPE)

SENSOR_77_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_77_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_78_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_78_TYPE)

SENSOR_78_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_78_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_78_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_78_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_78_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_78_TYPE)

SENSOR_78_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_78_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_79_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_79_TYPE)

SENSOR_79_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_79_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_79_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_79_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_79_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_79_TYPE)

SENSOR_79_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_79_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_80_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_80_TYPE)

SENSOR_80_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_80_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_80_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_80_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_80_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_80_TYPE)

SENSOR_80_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_80_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_81_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_81_TYPE)

SENSOR_81_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_81_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_81_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_81_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_81_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_81_TYPE)

SENSOR_81_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_81_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_82_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_82_TYPE)

SENSOR_82_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_82_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_82_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_82_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_82_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_82_TYPE)

SENSOR_82_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_82_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_83_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_83_TYPE)

SENSOR_83_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_83_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_83_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_83_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_83_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_83_TYPE)

SENSOR_83_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_83_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_84_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_84_TYPE)

SENSOR_84_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_84_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_84_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_84_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_84_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_84_TYPE)

SENSOR_84_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_84_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_85_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_85_TYPE)

SENSOR_85_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_85_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_85_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_85_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_85_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_85_TYPE)

SENSOR_85_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_85_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_86_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_86_TYPE)

SENSOR_86_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_86_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_86_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_86_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_86_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_86_TYPE)

SENSOR_86_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_86_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_87_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_87_TYPE)

SENSOR_87_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_87_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_87_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_87_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_87_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_87_TYPE)

SENSOR_87_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_87_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_88_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_88_TYPE)

SENSOR_88_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_88_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_88_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_88_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_88_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_88_TYPE)

SENSOR_88_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_88_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_89_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_89_TYPE)

SENSOR_89_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_89_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_89_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_89_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_89_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_89_TYPE)

SENSOR_89_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_89_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_90_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_90_TYPE)

SENSOR_90_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_90_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_90_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_90_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_90_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_90_TYPE)

SENSOR_90_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_90_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_91_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_91_TYPE)

SENSOR_91_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_91_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_91_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_91_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_91_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_91_TYPE)

SENSOR_91_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_91_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_92_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_92_TYPE)

SENSOR_92_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_92_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_92_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_92_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_92_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_92_TYPE)

SENSOR_92_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_92_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_93_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_93_TYPE)

SENSOR_93_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_93_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_93_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_93_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_93_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_93_TYPE)

SENSOR_93_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_93_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_94_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_94_TYPE)

SENSOR_94_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_94_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_94_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_94_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_94_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_94_TYPE)

SENSOR_94_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_94_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_95_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_95_TYPE)

SENSOR_95_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_95_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_95_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_95_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_95_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_95_TYPE)

SENSOR_95_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_95_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_96_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_96_TYPE)

SENSOR_96_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_96_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_96_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_96_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_96_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_96_TYPE)

SENSOR_96_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_96_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_97_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_97_TYPE)

SENSOR_97_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_97_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_97_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_97_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_97_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_97_TYPE)

SENSOR_97_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_97_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_98_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_98_TYPE)

SENSOR_98_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_98_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_98_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_98_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_98_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_98_TYPE)

SENSOR_98_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_98_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif


#ifdef SENSOR_99_PRESENT
	#if (SENSOR_ID_PWM_LED == SENSOR_99_TYPE)

SENSOR_99_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_99_ROLLING_TIMER_HIGH EQU memptr
memptr=memptr+1
SENSOR_99_PWM_VOLUME   		EQU memptr
memptr=memptr+1
SENSOR_99_PWM_TARGET 		EQU memptr
memptr=memptr+1
SENSOR_99_PWM_SPEED 			EQU memptr
memptr=memptr+1

	#endif

	#if (SENSOR_ID_TRIAC == SENSOR_99_TYPE)

SENSOR_99_ROLLING_TIMER_LOW	EQU memptr
memptr=memptr+1
SENSOR_99_PWM_VOLUME   		EQU memptr
memptr=memptr+1

	#endif
#endif

	endm

; invoke our nice shiny macro to place memory at compile-time
	placeinmemory h'A0'
