	EXTERN sendpacket
	EXTERN waitforpacket

CMD_PING			EQU H'01'
CMD_IDENT			EQU H'02'
CMD_GETSENSOR		EQU H'03'
CMD_SETSENSOR		EQU H'04'
CMD_GETSENSORTYPE	EQU H'05'
CMD_SETSENSORFADESPEED	EQU H'06'
CMD_SETPLOW			EQU H'07'
CMD_SETPHIGH		EQU H'08'
CMD_SETID			EQU H'09'
CMD_SET_KEY_BYTE	EQU H'0A'
CMD_RELOAD_FROM_FLASH	EQU H'0B'

; Note that errors returned from the PIC are 
; command-dependant and thus need parsing at
; the PC - side depending which command they 
; are returned from.

ERR_SENSOR_NONE				EQU H'00'

ERR_SET_SENSOR_NODE_NOT_FOUND	EQU H'01'
ERR_SET_SENSOR_NODE_WRONG_TYPE	EQU H'02'

ERR_GET_SENSOR_NODE_NOT_FOUND	EQU H'01'
ERR_GET_SENSOR_NODE_WRONG_TYPE	EQU H'02'

ERR_GET_SENSOR_TYPE_SNSR_NOT_FND	EQU H'01'

ERR_SET_SENSOR_FADE_NOT_FOUND	EQU H'01'
ERR_SET_SENSOR_FADE_WRONG_TYPE	EQU H'02'

#define SENSOR_ID_GENERIC_DIGITAL_IN	1
#define SENSOR_ID_GENERIC_DIGITAL_OUT	2
#define SENSOR_ID_PWM_LED				3
#define SENSOR_ID_TRIAC					4
#define SENSOR_ID_MULTILED				5
#define SENSOR_ID_MULTILED_MULTIPLEX	6

#define SENSOR_ID_COMPOSITE				d'200'

