; ************************************************ 
; **         THIS FILE IS AUTOGENERATED!        ** 
; ** YOU PROBABLY REALLY DON'T WANT TO EDIT IT! ** 
; ************************************************ 
; Source: template_cmd-get-sensor.asm

	#include "main.h"
	#include "sensorcfg.h"
	#include "processnamedcmd.asm"
	#include "debugger.h"
	#include "protocol.h"

	errorlevel  -302  

	CODE
do_cmd_get_sensor
	GLOBAL do_cmd_get_sensor
	; This command takes one byte  of input, being an
	; index to a sensor (eg. kettle temperature).This
	; is in packet7.

	; Upon an error, the topmost bit of packet5 will be set
	; and the error code will be placed in packet7. Success
	; results in the topmost bit being cleared and data
	; being returned in packet5 (bits 1-7) to packet7
	; A special case is sensor 0, which will output a
	; count of present sensors, in packet7.

	; Configure using the following:
	;define SENSOR_3_PRESENT		(mandatory)
	;define SENSOR_3_PORT PORTB		(port)
	;define SENSOR_3_TRIS TRISB		(tristate)
	;define SENSOR_3_PIN 1			(pin of both above)
	;define SENSOR_3_IS_INVERTING	(set for an inverting input
	;define SENSOR_3_TYPE SENSOR_ID_GENERIC_DIGITAL_IN	(mandatory)

	movlw DEBUGGER_GOT_CMD_GETSENSOR
	call debugger_spitvalue;

	; first, handle any requests for sensor 00
	movfw packet7
	btfsc STATUS, Z
	goto tellsensorcount
	
	; This block will be replicated once for every sensor, each with (AUTOGEN_EVERY_SENSOR_ID) replaced
   ; with an increasing sensor ID number. 
#ifdef SENSOR_0_PRESENT

	movfw packet7
	xorlw 0
	btfss STATUS, Z
	goto notthissensor_0

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_0_TYPE)

		clrf packet7
	#ifdef SENSOR_0_IS_INVERTING
		btfss SENSOR_0_PORT, SENSOR_0_PIN
	#else
		btfsc SENSOR_0_PORT, SENSOR_0_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_0
#endif
#ifdef SENSOR_1_PRESENT

	movfw packet7
	xorlw 1
	btfss STATUS, Z
	goto notthissensor_1

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_1_TYPE)

		clrf packet7
	#ifdef SENSOR_1_IS_INVERTING
		btfss SENSOR_1_PORT, SENSOR_1_PIN
	#else
		btfsc SENSOR_1_PORT, SENSOR_1_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_1
#endif
#ifdef SENSOR_2_PRESENT

	movfw packet7
	xorlw 2
	btfss STATUS, Z
	goto notthissensor_2

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_2_TYPE)

		clrf packet7
	#ifdef SENSOR_2_IS_INVERTING
		btfss SENSOR_2_PORT, SENSOR_2_PIN
	#else
		btfsc SENSOR_2_PORT, SENSOR_2_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_2
#endif
#ifdef SENSOR_3_PRESENT

	movfw packet7
	xorlw 3
	btfss STATUS, Z
	goto notthissensor_3

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_3_TYPE)

		clrf packet7
	#ifdef SENSOR_3_IS_INVERTING
		btfss SENSOR_3_PORT, SENSOR_3_PIN
	#else
		btfsc SENSOR_3_PORT, SENSOR_3_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_3
#endif
#ifdef SENSOR_4_PRESENT

	movfw packet7
	xorlw 4
	btfss STATUS, Z
	goto notthissensor_4

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_4_TYPE)

		clrf packet7
	#ifdef SENSOR_4_IS_INVERTING
		btfss SENSOR_4_PORT, SENSOR_4_PIN
	#else
		btfsc SENSOR_4_PORT, SENSOR_4_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_4
#endif
#ifdef SENSOR_5_PRESENT

	movfw packet7
	xorlw 5
	btfss STATUS, Z
	goto notthissensor_5

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_5_TYPE)

		clrf packet7
	#ifdef SENSOR_5_IS_INVERTING
		btfss SENSOR_5_PORT, SENSOR_5_PIN
	#else
		btfsc SENSOR_5_PORT, SENSOR_5_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_5
#endif
#ifdef SENSOR_6_PRESENT

	movfw packet7
	xorlw 6
	btfss STATUS, Z
	goto notthissensor_6

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_6_TYPE)

		clrf packet7
	#ifdef SENSOR_6_IS_INVERTING
		btfss SENSOR_6_PORT, SENSOR_6_PIN
	#else
		btfsc SENSOR_6_PORT, SENSOR_6_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_6
#endif
#ifdef SENSOR_7_PRESENT

	movfw packet7
	xorlw 7
	btfss STATUS, Z
	goto notthissensor_7

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_7_TYPE)

		clrf packet7
	#ifdef SENSOR_7_IS_INVERTING
		btfss SENSOR_7_PORT, SENSOR_7_PIN
	#else
		btfsc SENSOR_7_PORT, SENSOR_7_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_7
#endif
#ifdef SENSOR_8_PRESENT

	movfw packet7
	xorlw 8
	btfss STATUS, Z
	goto notthissensor_8

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_8_TYPE)

		clrf packet7
	#ifdef SENSOR_8_IS_INVERTING
		btfss SENSOR_8_PORT, SENSOR_8_PIN
	#else
		btfsc SENSOR_8_PORT, SENSOR_8_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_8
#endif
#ifdef SENSOR_9_PRESENT

	movfw packet7
	xorlw 9
	btfss STATUS, Z
	goto notthissensor_9

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_9_TYPE)

		clrf packet7
	#ifdef SENSOR_9_IS_INVERTING
		btfss SENSOR_9_PORT, SENSOR_9_PIN
	#else
		btfsc SENSOR_9_PORT, SENSOR_9_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_9
#endif
#ifdef SENSOR_10_PRESENT

	movfw packet7
	xorlw 10
	btfss STATUS, Z
	goto notthissensor_10

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_10_TYPE)

		clrf packet7
	#ifdef SENSOR_10_IS_INVERTING
		btfss SENSOR_10_PORT, SENSOR_10_PIN
	#else
		btfsc SENSOR_10_PORT, SENSOR_10_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_10
#endif
#ifdef SENSOR_11_PRESENT

	movfw packet7
	xorlw 11
	btfss STATUS, Z
	goto notthissensor_11

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_11_TYPE)

		clrf packet7
	#ifdef SENSOR_11_IS_INVERTING
		btfss SENSOR_11_PORT, SENSOR_11_PIN
	#else
		btfsc SENSOR_11_PORT, SENSOR_11_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_11
#endif
#ifdef SENSOR_12_PRESENT

	movfw packet7
	xorlw 12
	btfss STATUS, Z
	goto notthissensor_12

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_12_TYPE)

		clrf packet7
	#ifdef SENSOR_12_IS_INVERTING
		btfss SENSOR_12_PORT, SENSOR_12_PIN
	#else
		btfsc SENSOR_12_PORT, SENSOR_12_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_12
#endif
#ifdef SENSOR_13_PRESENT

	movfw packet7
	xorlw 13
	btfss STATUS, Z
	goto notthissensor_13

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_13_TYPE)

		clrf packet7
	#ifdef SENSOR_13_IS_INVERTING
		btfss SENSOR_13_PORT, SENSOR_13_PIN
	#else
		btfsc SENSOR_13_PORT, SENSOR_13_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_13
#endif
#ifdef SENSOR_14_PRESENT

	movfw packet7
	xorlw 14
	btfss STATUS, Z
	goto notthissensor_14

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_14_TYPE)

		clrf packet7
	#ifdef SENSOR_14_IS_INVERTING
		btfss SENSOR_14_PORT, SENSOR_14_PIN
	#else
		btfsc SENSOR_14_PORT, SENSOR_14_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_14
#endif
#ifdef SENSOR_15_PRESENT

	movfw packet7
	xorlw 15
	btfss STATUS, Z
	goto notthissensor_15

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_15_TYPE)

		clrf packet7
	#ifdef SENSOR_15_IS_INVERTING
		btfss SENSOR_15_PORT, SENSOR_15_PIN
	#else
		btfsc SENSOR_15_PORT, SENSOR_15_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_15
#endif
#ifdef SENSOR_16_PRESENT

	movfw packet7
	xorlw 16
	btfss STATUS, Z
	goto notthissensor_16

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_16_TYPE)

		clrf packet7
	#ifdef SENSOR_16_IS_INVERTING
		btfss SENSOR_16_PORT, SENSOR_16_PIN
	#else
		btfsc SENSOR_16_PORT, SENSOR_16_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_16
#endif
#ifdef SENSOR_17_PRESENT

	movfw packet7
	xorlw 17
	btfss STATUS, Z
	goto notthissensor_17

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_17_TYPE)

		clrf packet7
	#ifdef SENSOR_17_IS_INVERTING
		btfss SENSOR_17_PORT, SENSOR_17_PIN
	#else
		btfsc SENSOR_17_PORT, SENSOR_17_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_17
#endif
#ifdef SENSOR_18_PRESENT

	movfw packet7
	xorlw 18
	btfss STATUS, Z
	goto notthissensor_18

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_18_TYPE)

		clrf packet7
	#ifdef SENSOR_18_IS_INVERTING
		btfss SENSOR_18_PORT, SENSOR_18_PIN
	#else
		btfsc SENSOR_18_PORT, SENSOR_18_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_18
#endif
#ifdef SENSOR_19_PRESENT

	movfw packet7
	xorlw 19
	btfss STATUS, Z
	goto notthissensor_19

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_19_TYPE)

		clrf packet7
	#ifdef SENSOR_19_IS_INVERTING
		btfss SENSOR_19_PORT, SENSOR_19_PIN
	#else
		btfsc SENSOR_19_PORT, SENSOR_19_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_19
#endif
#ifdef SENSOR_20_PRESENT

	movfw packet7
	xorlw 20
	btfss STATUS, Z
	goto notthissensor_20

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_20_TYPE)

		clrf packet7
	#ifdef SENSOR_20_IS_INVERTING
		btfss SENSOR_20_PORT, SENSOR_20_PIN
	#else
		btfsc SENSOR_20_PORT, SENSOR_20_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_20
#endif
#ifdef SENSOR_21_PRESENT

	movfw packet7
	xorlw 21
	btfss STATUS, Z
	goto notthissensor_21

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_21_TYPE)

		clrf packet7
	#ifdef SENSOR_21_IS_INVERTING
		btfss SENSOR_21_PORT, SENSOR_21_PIN
	#else
		btfsc SENSOR_21_PORT, SENSOR_21_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_21
#endif
#ifdef SENSOR_22_PRESENT

	movfw packet7
	xorlw 22
	btfss STATUS, Z
	goto notthissensor_22

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_22_TYPE)

		clrf packet7
	#ifdef SENSOR_22_IS_INVERTING
		btfss SENSOR_22_PORT, SENSOR_22_PIN
	#else
		btfsc SENSOR_22_PORT, SENSOR_22_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_22
#endif
#ifdef SENSOR_23_PRESENT

	movfw packet7
	xorlw 23
	btfss STATUS, Z
	goto notthissensor_23

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_23_TYPE)

		clrf packet7
	#ifdef SENSOR_23_IS_INVERTING
		btfss SENSOR_23_PORT, SENSOR_23_PIN
	#else
		btfsc SENSOR_23_PORT, SENSOR_23_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_23
#endif
#ifdef SENSOR_24_PRESENT

	movfw packet7
	xorlw 24
	btfss STATUS, Z
	goto notthissensor_24

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_24_TYPE)

		clrf packet7
	#ifdef SENSOR_24_IS_INVERTING
		btfss SENSOR_24_PORT, SENSOR_24_PIN
	#else
		btfsc SENSOR_24_PORT, SENSOR_24_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_24
#endif
#ifdef SENSOR_25_PRESENT

	movfw packet7
	xorlw 25
	btfss STATUS, Z
	goto notthissensor_25

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_25_TYPE)

		clrf packet7
	#ifdef SENSOR_25_IS_INVERTING
		btfss SENSOR_25_PORT, SENSOR_25_PIN
	#else
		btfsc SENSOR_25_PORT, SENSOR_25_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_25
#endif
#ifdef SENSOR_26_PRESENT

	movfw packet7
	xorlw 26
	btfss STATUS, Z
	goto notthissensor_26

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_26_TYPE)

		clrf packet7
	#ifdef SENSOR_26_IS_INVERTING
		btfss SENSOR_26_PORT, SENSOR_26_PIN
	#else
		btfsc SENSOR_26_PORT, SENSOR_26_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_26
#endif
#ifdef SENSOR_27_PRESENT

	movfw packet7
	xorlw 27
	btfss STATUS, Z
	goto notthissensor_27

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_27_TYPE)

		clrf packet7
	#ifdef SENSOR_27_IS_INVERTING
		btfss SENSOR_27_PORT, SENSOR_27_PIN
	#else
		btfsc SENSOR_27_PORT, SENSOR_27_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_27
#endif
#ifdef SENSOR_28_PRESENT

	movfw packet7
	xorlw 28
	btfss STATUS, Z
	goto notthissensor_28

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_28_TYPE)

		clrf packet7
	#ifdef SENSOR_28_IS_INVERTING
		btfss SENSOR_28_PORT, SENSOR_28_PIN
	#else
		btfsc SENSOR_28_PORT, SENSOR_28_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_28
#endif
#ifdef SENSOR_29_PRESENT

	movfw packet7
	xorlw 29
	btfss STATUS, Z
	goto notthissensor_29

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_29_TYPE)

		clrf packet7
	#ifdef SENSOR_29_IS_INVERTING
		btfss SENSOR_29_PORT, SENSOR_29_PIN
	#else
		btfsc SENSOR_29_PORT, SENSOR_29_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_29
#endif
#ifdef SENSOR_30_PRESENT

	movfw packet7
	xorlw 30
	btfss STATUS, Z
	goto notthissensor_30

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_30_TYPE)

		clrf packet7
	#ifdef SENSOR_30_IS_INVERTING
		btfss SENSOR_30_PORT, SENSOR_30_PIN
	#else
		btfsc SENSOR_30_PORT, SENSOR_30_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_30
#endif
#ifdef SENSOR_31_PRESENT

	movfw packet7
	xorlw 31
	btfss STATUS, Z
	goto notthissensor_31

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_31_TYPE)

		clrf packet7
	#ifdef SENSOR_31_IS_INVERTING
		btfss SENSOR_31_PORT, SENSOR_31_PIN
	#else
		btfsc SENSOR_31_PORT, SENSOR_31_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_31
#endif
#ifdef SENSOR_32_PRESENT

	movfw packet7
	xorlw 32
	btfss STATUS, Z
	goto notthissensor_32

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_32_TYPE)

		clrf packet7
	#ifdef SENSOR_32_IS_INVERTING
		btfss SENSOR_32_PORT, SENSOR_32_PIN
	#else
		btfsc SENSOR_32_PORT, SENSOR_32_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_32
#endif
#ifdef SENSOR_33_PRESENT

	movfw packet7
	xorlw 33
	btfss STATUS, Z
	goto notthissensor_33

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_33_TYPE)

		clrf packet7
	#ifdef SENSOR_33_IS_INVERTING
		btfss SENSOR_33_PORT, SENSOR_33_PIN
	#else
		btfsc SENSOR_33_PORT, SENSOR_33_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_33
#endif
#ifdef SENSOR_34_PRESENT

	movfw packet7
	xorlw 34
	btfss STATUS, Z
	goto notthissensor_34

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_34_TYPE)

		clrf packet7
	#ifdef SENSOR_34_IS_INVERTING
		btfss SENSOR_34_PORT, SENSOR_34_PIN
	#else
		btfsc SENSOR_34_PORT, SENSOR_34_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_34
#endif
#ifdef SENSOR_35_PRESENT

	movfw packet7
	xorlw 35
	btfss STATUS, Z
	goto notthissensor_35

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_35_TYPE)

		clrf packet7
	#ifdef SENSOR_35_IS_INVERTING
		btfss SENSOR_35_PORT, SENSOR_35_PIN
	#else
		btfsc SENSOR_35_PORT, SENSOR_35_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_35
#endif
#ifdef SENSOR_36_PRESENT

	movfw packet7
	xorlw 36
	btfss STATUS, Z
	goto notthissensor_36

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_36_TYPE)

		clrf packet7
	#ifdef SENSOR_36_IS_INVERTING
		btfss SENSOR_36_PORT, SENSOR_36_PIN
	#else
		btfsc SENSOR_36_PORT, SENSOR_36_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_36
#endif
#ifdef SENSOR_37_PRESENT

	movfw packet7
	xorlw 37
	btfss STATUS, Z
	goto notthissensor_37

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_37_TYPE)

		clrf packet7
	#ifdef SENSOR_37_IS_INVERTING
		btfss SENSOR_37_PORT, SENSOR_37_PIN
	#else
		btfsc SENSOR_37_PORT, SENSOR_37_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_37
#endif
#ifdef SENSOR_38_PRESENT

	movfw packet7
	xorlw 38
	btfss STATUS, Z
	goto notthissensor_38

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_38_TYPE)

		clrf packet7
	#ifdef SENSOR_38_IS_INVERTING
		btfss SENSOR_38_PORT, SENSOR_38_PIN
	#else
		btfsc SENSOR_38_PORT, SENSOR_38_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_38
#endif
#ifdef SENSOR_39_PRESENT

	movfw packet7
	xorlw 39
	btfss STATUS, Z
	goto notthissensor_39

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_39_TYPE)

		clrf packet7
	#ifdef SENSOR_39_IS_INVERTING
		btfss SENSOR_39_PORT, SENSOR_39_PIN
	#else
		btfsc SENSOR_39_PORT, SENSOR_39_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_39
#endif
#ifdef SENSOR_40_PRESENT

	movfw packet7
	xorlw 40
	btfss STATUS, Z
	goto notthissensor_40

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_40_TYPE)

		clrf packet7
	#ifdef SENSOR_40_IS_INVERTING
		btfss SENSOR_40_PORT, SENSOR_40_PIN
	#else
		btfsc SENSOR_40_PORT, SENSOR_40_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_40
#endif
#ifdef SENSOR_41_PRESENT

	movfw packet7
	xorlw 41
	btfss STATUS, Z
	goto notthissensor_41

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_41_TYPE)

		clrf packet7
	#ifdef SENSOR_41_IS_INVERTING
		btfss SENSOR_41_PORT, SENSOR_41_PIN
	#else
		btfsc SENSOR_41_PORT, SENSOR_41_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_41
#endif
#ifdef SENSOR_42_PRESENT

	movfw packet7
	xorlw 42
	btfss STATUS, Z
	goto notthissensor_42

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_42_TYPE)

		clrf packet7
	#ifdef SENSOR_42_IS_INVERTING
		btfss SENSOR_42_PORT, SENSOR_42_PIN
	#else
		btfsc SENSOR_42_PORT, SENSOR_42_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_42
#endif
#ifdef SENSOR_43_PRESENT

	movfw packet7
	xorlw 43
	btfss STATUS, Z
	goto notthissensor_43

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_43_TYPE)

		clrf packet7
	#ifdef SENSOR_43_IS_INVERTING
		btfss SENSOR_43_PORT, SENSOR_43_PIN
	#else
		btfsc SENSOR_43_PORT, SENSOR_43_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_43
#endif
#ifdef SENSOR_44_PRESENT

	movfw packet7
	xorlw 44
	btfss STATUS, Z
	goto notthissensor_44

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_44_TYPE)

		clrf packet7
	#ifdef SENSOR_44_IS_INVERTING
		btfss SENSOR_44_PORT, SENSOR_44_PIN
	#else
		btfsc SENSOR_44_PORT, SENSOR_44_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_44
#endif
#ifdef SENSOR_45_PRESENT

	movfw packet7
	xorlw 45
	btfss STATUS, Z
	goto notthissensor_45

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_45_TYPE)

		clrf packet7
	#ifdef SENSOR_45_IS_INVERTING
		btfss SENSOR_45_PORT, SENSOR_45_PIN
	#else
		btfsc SENSOR_45_PORT, SENSOR_45_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_45
#endif
#ifdef SENSOR_46_PRESENT

	movfw packet7
	xorlw 46
	btfss STATUS, Z
	goto notthissensor_46

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_46_TYPE)

		clrf packet7
	#ifdef SENSOR_46_IS_INVERTING
		btfss SENSOR_46_PORT, SENSOR_46_PIN
	#else
		btfsc SENSOR_46_PORT, SENSOR_46_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_46
#endif
#ifdef SENSOR_47_PRESENT

	movfw packet7
	xorlw 47
	btfss STATUS, Z
	goto notthissensor_47

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_47_TYPE)

		clrf packet7
	#ifdef SENSOR_47_IS_INVERTING
		btfss SENSOR_47_PORT, SENSOR_47_PIN
	#else
		btfsc SENSOR_47_PORT, SENSOR_47_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_47
#endif
#ifdef SENSOR_48_PRESENT

	movfw packet7
	xorlw 48
	btfss STATUS, Z
	goto notthissensor_48

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_48_TYPE)

		clrf packet7
	#ifdef SENSOR_48_IS_INVERTING
		btfss SENSOR_48_PORT, SENSOR_48_PIN
	#else
		btfsc SENSOR_48_PORT, SENSOR_48_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_48
#endif
#ifdef SENSOR_49_PRESENT

	movfw packet7
	xorlw 49
	btfss STATUS, Z
	goto notthissensor_49

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_49_TYPE)

		clrf packet7
	#ifdef SENSOR_49_IS_INVERTING
		btfss SENSOR_49_PORT, SENSOR_49_PIN
	#else
		btfsc SENSOR_49_PORT, SENSOR_49_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_49
#endif
#ifdef SENSOR_50_PRESENT

	movfw packet7
	xorlw 50
	btfss STATUS, Z
	goto notthissensor_50

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_50_TYPE)

		clrf packet7
	#ifdef SENSOR_50_IS_INVERTING
		btfss SENSOR_50_PORT, SENSOR_50_PIN
	#else
		btfsc SENSOR_50_PORT, SENSOR_50_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_50
#endif
#ifdef SENSOR_51_PRESENT

	movfw packet7
	xorlw 51
	btfss STATUS, Z
	goto notthissensor_51

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_51_TYPE)

		clrf packet7
	#ifdef SENSOR_51_IS_INVERTING
		btfss SENSOR_51_PORT, SENSOR_51_PIN
	#else
		btfsc SENSOR_51_PORT, SENSOR_51_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_51
#endif
#ifdef SENSOR_52_PRESENT

	movfw packet7
	xorlw 52
	btfss STATUS, Z
	goto notthissensor_52

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_52_TYPE)

		clrf packet7
	#ifdef SENSOR_52_IS_INVERTING
		btfss SENSOR_52_PORT, SENSOR_52_PIN
	#else
		btfsc SENSOR_52_PORT, SENSOR_52_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_52
#endif
#ifdef SENSOR_53_PRESENT

	movfw packet7
	xorlw 53
	btfss STATUS, Z
	goto notthissensor_53

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_53_TYPE)

		clrf packet7
	#ifdef SENSOR_53_IS_INVERTING
		btfss SENSOR_53_PORT, SENSOR_53_PIN
	#else
		btfsc SENSOR_53_PORT, SENSOR_53_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_53
#endif
#ifdef SENSOR_54_PRESENT

	movfw packet7
	xorlw 54
	btfss STATUS, Z
	goto notthissensor_54

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_54_TYPE)

		clrf packet7
	#ifdef SENSOR_54_IS_INVERTING
		btfss SENSOR_54_PORT, SENSOR_54_PIN
	#else
		btfsc SENSOR_54_PORT, SENSOR_54_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_54
#endif
#ifdef SENSOR_55_PRESENT

	movfw packet7
	xorlw 55
	btfss STATUS, Z
	goto notthissensor_55

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_55_TYPE)

		clrf packet7
	#ifdef SENSOR_55_IS_INVERTING
		btfss SENSOR_55_PORT, SENSOR_55_PIN
	#else
		btfsc SENSOR_55_PORT, SENSOR_55_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_55
#endif
#ifdef SENSOR_56_PRESENT

	movfw packet7
	xorlw 56
	btfss STATUS, Z
	goto notthissensor_56

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_56_TYPE)

		clrf packet7
	#ifdef SENSOR_56_IS_INVERTING
		btfss SENSOR_56_PORT, SENSOR_56_PIN
	#else
		btfsc SENSOR_56_PORT, SENSOR_56_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_56
#endif
#ifdef SENSOR_57_PRESENT

	movfw packet7
	xorlw 57
	btfss STATUS, Z
	goto notthissensor_57

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_57_TYPE)

		clrf packet7
	#ifdef SENSOR_57_IS_INVERTING
		btfss SENSOR_57_PORT, SENSOR_57_PIN
	#else
		btfsc SENSOR_57_PORT, SENSOR_57_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_57
#endif
#ifdef SENSOR_58_PRESENT

	movfw packet7
	xorlw 58
	btfss STATUS, Z
	goto notthissensor_58

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_58_TYPE)

		clrf packet7
	#ifdef SENSOR_58_IS_INVERTING
		btfss SENSOR_58_PORT, SENSOR_58_PIN
	#else
		btfsc SENSOR_58_PORT, SENSOR_58_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_58
#endif
#ifdef SENSOR_59_PRESENT

	movfw packet7
	xorlw 59
	btfss STATUS, Z
	goto notthissensor_59

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_59_TYPE)

		clrf packet7
	#ifdef SENSOR_59_IS_INVERTING
		btfss SENSOR_59_PORT, SENSOR_59_PIN
	#else
		btfsc SENSOR_59_PORT, SENSOR_59_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_59
#endif
#ifdef SENSOR_60_PRESENT

	movfw packet7
	xorlw 60
	btfss STATUS, Z
	goto notthissensor_60

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_60_TYPE)

		clrf packet7
	#ifdef SENSOR_60_IS_INVERTING
		btfss SENSOR_60_PORT, SENSOR_60_PIN
	#else
		btfsc SENSOR_60_PORT, SENSOR_60_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_60
#endif
#ifdef SENSOR_61_PRESENT

	movfw packet7
	xorlw 61
	btfss STATUS, Z
	goto notthissensor_61

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_61_TYPE)

		clrf packet7
	#ifdef SENSOR_61_IS_INVERTING
		btfss SENSOR_61_PORT, SENSOR_61_PIN
	#else
		btfsc SENSOR_61_PORT, SENSOR_61_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_61
#endif
#ifdef SENSOR_62_PRESENT

	movfw packet7
	xorlw 62
	btfss STATUS, Z
	goto notthissensor_62

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_62_TYPE)

		clrf packet7
	#ifdef SENSOR_62_IS_INVERTING
		btfss SENSOR_62_PORT, SENSOR_62_PIN
	#else
		btfsc SENSOR_62_PORT, SENSOR_62_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_62
#endif
#ifdef SENSOR_63_PRESENT

	movfw packet7
	xorlw 63
	btfss STATUS, Z
	goto notthissensor_63

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_63_TYPE)

		clrf packet7
	#ifdef SENSOR_63_IS_INVERTING
		btfss SENSOR_63_PORT, SENSOR_63_PIN
	#else
		btfsc SENSOR_63_PORT, SENSOR_63_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_63
#endif
#ifdef SENSOR_64_PRESENT

	movfw packet7
	xorlw 64
	btfss STATUS, Z
	goto notthissensor_64

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_64_TYPE)

		clrf packet7
	#ifdef SENSOR_64_IS_INVERTING
		btfss SENSOR_64_PORT, SENSOR_64_PIN
	#else
		btfsc SENSOR_64_PORT, SENSOR_64_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_64
#endif
#ifdef SENSOR_65_PRESENT

	movfw packet7
	xorlw 65
	btfss STATUS, Z
	goto notthissensor_65

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_65_TYPE)

		clrf packet7
	#ifdef SENSOR_65_IS_INVERTING
		btfss SENSOR_65_PORT, SENSOR_65_PIN
	#else
		btfsc SENSOR_65_PORT, SENSOR_65_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_65
#endif
#ifdef SENSOR_66_PRESENT

	movfw packet7
	xorlw 66
	btfss STATUS, Z
	goto notthissensor_66

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_66_TYPE)

		clrf packet7
	#ifdef SENSOR_66_IS_INVERTING
		btfss SENSOR_66_PORT, SENSOR_66_PIN
	#else
		btfsc SENSOR_66_PORT, SENSOR_66_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_66
#endif
#ifdef SENSOR_67_PRESENT

	movfw packet7
	xorlw 67
	btfss STATUS, Z
	goto notthissensor_67

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_67_TYPE)

		clrf packet7
	#ifdef SENSOR_67_IS_INVERTING
		btfss SENSOR_67_PORT, SENSOR_67_PIN
	#else
		btfsc SENSOR_67_PORT, SENSOR_67_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_67
#endif
#ifdef SENSOR_68_PRESENT

	movfw packet7
	xorlw 68
	btfss STATUS, Z
	goto notthissensor_68

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_68_TYPE)

		clrf packet7
	#ifdef SENSOR_68_IS_INVERTING
		btfss SENSOR_68_PORT, SENSOR_68_PIN
	#else
		btfsc SENSOR_68_PORT, SENSOR_68_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_68
#endif
#ifdef SENSOR_69_PRESENT

	movfw packet7
	xorlw 69
	btfss STATUS, Z
	goto notthissensor_69

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_69_TYPE)

		clrf packet7
	#ifdef SENSOR_69_IS_INVERTING
		btfss SENSOR_69_PORT, SENSOR_69_PIN
	#else
		btfsc SENSOR_69_PORT, SENSOR_69_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_69
#endif
#ifdef SENSOR_70_PRESENT

	movfw packet7
	xorlw 70
	btfss STATUS, Z
	goto notthissensor_70

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_70_TYPE)

		clrf packet7
	#ifdef SENSOR_70_IS_INVERTING
		btfss SENSOR_70_PORT, SENSOR_70_PIN
	#else
		btfsc SENSOR_70_PORT, SENSOR_70_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_70
#endif
#ifdef SENSOR_71_PRESENT

	movfw packet7
	xorlw 71
	btfss STATUS, Z
	goto notthissensor_71

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_71_TYPE)

		clrf packet7
	#ifdef SENSOR_71_IS_INVERTING
		btfss SENSOR_71_PORT, SENSOR_71_PIN
	#else
		btfsc SENSOR_71_PORT, SENSOR_71_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_71
#endif
#ifdef SENSOR_72_PRESENT

	movfw packet7
	xorlw 72
	btfss STATUS, Z
	goto notthissensor_72

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_72_TYPE)

		clrf packet7
	#ifdef SENSOR_72_IS_INVERTING
		btfss SENSOR_72_PORT, SENSOR_72_PIN
	#else
		btfsc SENSOR_72_PORT, SENSOR_72_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_72
#endif
#ifdef SENSOR_73_PRESENT

	movfw packet7
	xorlw 73
	btfss STATUS, Z
	goto notthissensor_73

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_73_TYPE)

		clrf packet7
	#ifdef SENSOR_73_IS_INVERTING
		btfss SENSOR_73_PORT, SENSOR_73_PIN
	#else
		btfsc SENSOR_73_PORT, SENSOR_73_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_73
#endif
#ifdef SENSOR_74_PRESENT

	movfw packet7
	xorlw 74
	btfss STATUS, Z
	goto notthissensor_74

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_74_TYPE)

		clrf packet7
	#ifdef SENSOR_74_IS_INVERTING
		btfss SENSOR_74_PORT, SENSOR_74_PIN
	#else
		btfsc SENSOR_74_PORT, SENSOR_74_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_74
#endif
#ifdef SENSOR_75_PRESENT

	movfw packet7
	xorlw 75
	btfss STATUS, Z
	goto notthissensor_75

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_75_TYPE)

		clrf packet7
	#ifdef SENSOR_75_IS_INVERTING
		btfss SENSOR_75_PORT, SENSOR_75_PIN
	#else
		btfsc SENSOR_75_PORT, SENSOR_75_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_75
#endif
#ifdef SENSOR_76_PRESENT

	movfw packet7
	xorlw 76
	btfss STATUS, Z
	goto notthissensor_76

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_76_TYPE)

		clrf packet7
	#ifdef SENSOR_76_IS_INVERTING
		btfss SENSOR_76_PORT, SENSOR_76_PIN
	#else
		btfsc SENSOR_76_PORT, SENSOR_76_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_76
#endif
#ifdef SENSOR_77_PRESENT

	movfw packet7
	xorlw 77
	btfss STATUS, Z
	goto notthissensor_77

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_77_TYPE)

		clrf packet7
	#ifdef SENSOR_77_IS_INVERTING
		btfss SENSOR_77_PORT, SENSOR_77_PIN
	#else
		btfsc SENSOR_77_PORT, SENSOR_77_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_77
#endif
#ifdef SENSOR_78_PRESENT

	movfw packet7
	xorlw 78
	btfss STATUS, Z
	goto notthissensor_78

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_78_TYPE)

		clrf packet7
	#ifdef SENSOR_78_IS_INVERTING
		btfss SENSOR_78_PORT, SENSOR_78_PIN
	#else
		btfsc SENSOR_78_PORT, SENSOR_78_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_78
#endif
#ifdef SENSOR_79_PRESENT

	movfw packet7
	xorlw 79
	btfss STATUS, Z
	goto notthissensor_79

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_79_TYPE)

		clrf packet7
	#ifdef SENSOR_79_IS_INVERTING
		btfss SENSOR_79_PORT, SENSOR_79_PIN
	#else
		btfsc SENSOR_79_PORT, SENSOR_79_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_79
#endif
#ifdef SENSOR_80_PRESENT

	movfw packet7
	xorlw 80
	btfss STATUS, Z
	goto notthissensor_80

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_80_TYPE)

		clrf packet7
	#ifdef SENSOR_80_IS_INVERTING
		btfss SENSOR_80_PORT, SENSOR_80_PIN
	#else
		btfsc SENSOR_80_PORT, SENSOR_80_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_80
#endif
#ifdef SENSOR_81_PRESENT

	movfw packet7
	xorlw 81
	btfss STATUS, Z
	goto notthissensor_81

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_81_TYPE)

		clrf packet7
	#ifdef SENSOR_81_IS_INVERTING
		btfss SENSOR_81_PORT, SENSOR_81_PIN
	#else
		btfsc SENSOR_81_PORT, SENSOR_81_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_81
#endif
#ifdef SENSOR_82_PRESENT

	movfw packet7
	xorlw 82
	btfss STATUS, Z
	goto notthissensor_82

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_82_TYPE)

		clrf packet7
	#ifdef SENSOR_82_IS_INVERTING
		btfss SENSOR_82_PORT, SENSOR_82_PIN
	#else
		btfsc SENSOR_82_PORT, SENSOR_82_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_82
#endif
#ifdef SENSOR_83_PRESENT

	movfw packet7
	xorlw 83
	btfss STATUS, Z
	goto notthissensor_83

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_83_TYPE)

		clrf packet7
	#ifdef SENSOR_83_IS_INVERTING
		btfss SENSOR_83_PORT, SENSOR_83_PIN
	#else
		btfsc SENSOR_83_PORT, SENSOR_83_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_83
#endif
#ifdef SENSOR_84_PRESENT

	movfw packet7
	xorlw 84
	btfss STATUS, Z
	goto notthissensor_84

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_84_TYPE)

		clrf packet7
	#ifdef SENSOR_84_IS_INVERTING
		btfss SENSOR_84_PORT, SENSOR_84_PIN
	#else
		btfsc SENSOR_84_PORT, SENSOR_84_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_84
#endif
#ifdef SENSOR_85_PRESENT

	movfw packet7
	xorlw 85
	btfss STATUS, Z
	goto notthissensor_85

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_85_TYPE)

		clrf packet7
	#ifdef SENSOR_85_IS_INVERTING
		btfss SENSOR_85_PORT, SENSOR_85_PIN
	#else
		btfsc SENSOR_85_PORT, SENSOR_85_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_85
#endif
#ifdef SENSOR_86_PRESENT

	movfw packet7
	xorlw 86
	btfss STATUS, Z
	goto notthissensor_86

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_86_TYPE)

		clrf packet7
	#ifdef SENSOR_86_IS_INVERTING
		btfss SENSOR_86_PORT, SENSOR_86_PIN
	#else
		btfsc SENSOR_86_PORT, SENSOR_86_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_86
#endif
#ifdef SENSOR_87_PRESENT

	movfw packet7
	xorlw 87
	btfss STATUS, Z
	goto notthissensor_87

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_87_TYPE)

		clrf packet7
	#ifdef SENSOR_87_IS_INVERTING
		btfss SENSOR_87_PORT, SENSOR_87_PIN
	#else
		btfsc SENSOR_87_PORT, SENSOR_87_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_87
#endif
#ifdef SENSOR_88_PRESENT

	movfw packet7
	xorlw 88
	btfss STATUS, Z
	goto notthissensor_88

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_88_TYPE)

		clrf packet7
	#ifdef SENSOR_88_IS_INVERTING
		btfss SENSOR_88_PORT, SENSOR_88_PIN
	#else
		btfsc SENSOR_88_PORT, SENSOR_88_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_88
#endif
#ifdef SENSOR_89_PRESENT

	movfw packet7
	xorlw 89
	btfss STATUS, Z
	goto notthissensor_89

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_89_TYPE)

		clrf packet7
	#ifdef SENSOR_89_IS_INVERTING
		btfss SENSOR_89_PORT, SENSOR_89_PIN
	#else
		btfsc SENSOR_89_PORT, SENSOR_89_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_89
#endif
#ifdef SENSOR_90_PRESENT

	movfw packet7
	xorlw 90
	btfss STATUS, Z
	goto notthissensor_90

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_90_TYPE)

		clrf packet7
	#ifdef SENSOR_90_IS_INVERTING
		btfss SENSOR_90_PORT, SENSOR_90_PIN
	#else
		btfsc SENSOR_90_PORT, SENSOR_90_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_90
#endif
#ifdef SENSOR_91_PRESENT

	movfw packet7
	xorlw 91
	btfss STATUS, Z
	goto notthissensor_91

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_91_TYPE)

		clrf packet7
	#ifdef SENSOR_91_IS_INVERTING
		btfss SENSOR_91_PORT, SENSOR_91_PIN
	#else
		btfsc SENSOR_91_PORT, SENSOR_91_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_91
#endif
#ifdef SENSOR_92_PRESENT

	movfw packet7
	xorlw 92
	btfss STATUS, Z
	goto notthissensor_92

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_92_TYPE)

		clrf packet7
	#ifdef SENSOR_92_IS_INVERTING
		btfss SENSOR_92_PORT, SENSOR_92_PIN
	#else
		btfsc SENSOR_92_PORT, SENSOR_92_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_92
#endif
#ifdef SENSOR_93_PRESENT

	movfw packet7
	xorlw 93
	btfss STATUS, Z
	goto notthissensor_93

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_93_TYPE)

		clrf packet7
	#ifdef SENSOR_93_IS_INVERTING
		btfss SENSOR_93_PORT, SENSOR_93_PIN
	#else
		btfsc SENSOR_93_PORT, SENSOR_93_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_93
#endif
#ifdef SENSOR_94_PRESENT

	movfw packet7
	xorlw 94
	btfss STATUS, Z
	goto notthissensor_94

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_94_TYPE)

		clrf packet7
	#ifdef SENSOR_94_IS_INVERTING
		btfss SENSOR_94_PORT, SENSOR_94_PIN
	#else
		btfsc SENSOR_94_PORT, SENSOR_94_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_94
#endif
#ifdef SENSOR_95_PRESENT

	movfw packet7
	xorlw 95
	btfss STATUS, Z
	goto notthissensor_95

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_95_TYPE)

		clrf packet7
	#ifdef SENSOR_95_IS_INVERTING
		btfss SENSOR_95_PORT, SENSOR_95_PIN
	#else
		btfsc SENSOR_95_PORT, SENSOR_95_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_95
#endif
#ifdef SENSOR_96_PRESENT

	movfw packet7
	xorlw 96
	btfss STATUS, Z
	goto notthissensor_96

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_96_TYPE)

		clrf packet7
	#ifdef SENSOR_96_IS_INVERTING
		btfss SENSOR_96_PORT, SENSOR_96_PIN
	#else
		btfsc SENSOR_96_PORT, SENSOR_96_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_96
#endif
#ifdef SENSOR_97_PRESENT

	movfw packet7
	xorlw 97
	btfss STATUS, Z
	goto notthissensor_97

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_97_TYPE)

		clrf packet7
	#ifdef SENSOR_97_IS_INVERTING
		btfss SENSOR_97_PORT, SENSOR_97_PIN
	#else
		btfsc SENSOR_97_PORT, SENSOR_97_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_97
#endif
#ifdef SENSOR_98_PRESENT

	movfw packet7
	xorlw 98
	btfss STATUS, Z
	goto notthissensor_98

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_98_TYPE)

		clrf packet7
	#ifdef SENSOR_98_IS_INVERTING
		btfss SENSOR_98_PORT, SENSOR_98_PIN
	#else
		btfsc SENSOR_98_PORT, SENSOR_98_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_98
#endif
#ifdef SENSOR_99_PRESENT

	movfw packet7
	xorlw 99
	btfss STATUS, Z
	goto notthissensor_99

	#if (SENSOR_ID_GENERIC_DIGITAL_IN == SENSOR_99_TYPE)

		clrf packet7
	#ifdef SENSOR_99_IS_INVERTING
		btfss SENSOR_99_PORT, SENSOR_99_PIN
	#else
		btfsc SENSOR_99_PORT, SENSOR_99_PIN
	#endif
		bsf packet7, 0
		goto cmd_get_return_ok
	#else
		goto cmd_get_return_wrong_type
	#endif
notthissensor_99
#endif
	; If we get here, we don't know this sensor (none of the above goto's have been taken). Respond with
	; a failure code.
	movlw DEBUGGER_UNKNOWN_SENSOR
	call debugger_spitvalue;

	clrf packet4	
	clrf packet5
	clrf packet6

	bsf packet5, 0	; signal error
	movlw ERR_GET_SENSOR_NODE_NOT_FOUND	; set error code
	movwf packet7
	return
	
cmd_get_return_wrong_type:
	clrf packet4	
	clrf packet5
	clrf packet6
	bsf packet5, 0	; signal error
	movlw ERR_GET_SENSOR_NODE_WRONG_TYPE	; set error code
	movwf packet7
	return

cmd_get_return_ok:
	clrf packet4
	clrf packet5
	clrf packet6
;	bcf packet4, 0
	return

tellsensorcount:
	movlw SENSOR_COUNT
	movwf packet7
	clrf packet6
	clrf packet5
	clrf packet4
	return

	end
