; ************************************************ 
; **         THIS FILE IS AUTOGENERATED!        ** 
; ** YOU PROBABLY REALLY DON'T WANT TO EDIT IT! ** 
; ************************************************ 
; Source: template_cmd-get-sensor-type.asm

	#include "main.h"
	#include "sensorcfg.h"
	#include "processnamedcmd.asm"
	#include "debugger.h"
	#include "protocol.h"

	errorlevel  -302  

	CODE
do_cmd_get_sensor_type
	GLOBAL do_cmd_get_sensor_type
	; This command takes one byte  of input, being an
	; index to a sensor. This is in packet5. It responds
	; with a number indicating the sensor type, eg,
	; a SENSOR_ID_GENERIC_DIGITAL_IN would return 1.
	; definitions are in protocol.h.

	; Upon an error, the topmost bit of packet5 will be set
	; and the error code will be placed in packet7. Success
	; results in the topmost bit of packet5 being cleared,
	; and data being returned in packet7.

	clrf packet6

	; Check the host hasn't requested a sensor index greater
	; than our sensor count
	movfw packet5
	sublw SENSOR_COUNT
	btfsc STATUS, Z
	goto sensor_not_found

	; Loop through every sensor, 
#ifdef SENSOR_0_PRESENT
	movfw packet7
	xorlw 0
	btfss STATUS,Z
	goto notthissensor_0
	; This sensor is being addressed
	#if (SENSOR_0_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_0_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_0:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_1_PRESENT
	movfw packet7
	xorlw 1
	btfss STATUS,Z
	goto notthissensor_1
	; This sensor is being addressed
	#if (SENSOR_1_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_1_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_1:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_2_PRESENT
	movfw packet7
	xorlw 2
	btfss STATUS,Z
	goto notthissensor_2
	; This sensor is being addressed
	#if (SENSOR_2_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_2_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_2:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_3_PRESENT
	movfw packet7
	xorlw 3
	btfss STATUS,Z
	goto notthissensor_3
	; This sensor is being addressed
	#if (SENSOR_3_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_3_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_3:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_4_PRESENT
	movfw packet7
	xorlw 4
	btfss STATUS,Z
	goto notthissensor_4
	; This sensor is being addressed
	#if (SENSOR_4_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_4_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_4:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_5_PRESENT
	movfw packet7
	xorlw 5
	btfss STATUS,Z
	goto notthissensor_5
	; This sensor is being addressed
	#if (SENSOR_5_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_5_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_5:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_6_PRESENT
	movfw packet7
	xorlw 6
	btfss STATUS,Z
	goto notthissensor_6
	; This sensor is being addressed
	#if (SENSOR_6_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_6_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_6:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_7_PRESENT
	movfw packet7
	xorlw 7
	btfss STATUS,Z
	goto notthissensor_7
	; This sensor is being addressed
	#if (SENSOR_7_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_7_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_7:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_8_PRESENT
	movfw packet7
	xorlw 8
	btfss STATUS,Z
	goto notthissensor_8
	; This sensor is being addressed
	#if (SENSOR_8_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_8_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_8:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_9_PRESENT
	movfw packet7
	xorlw 9
	btfss STATUS,Z
	goto notthissensor_9
	; This sensor is being addressed
	#if (SENSOR_9_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_9_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_9:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_10_PRESENT
	movfw packet7
	xorlw 10
	btfss STATUS,Z
	goto notthissensor_10
	; This sensor is being addressed
	#if (SENSOR_10_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_10_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_10:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_11_PRESENT
	movfw packet7
	xorlw 11
	btfss STATUS,Z
	goto notthissensor_11
	; This sensor is being addressed
	#if (SENSOR_11_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_11_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_11:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_12_PRESENT
	movfw packet7
	xorlw 12
	btfss STATUS,Z
	goto notthissensor_12
	; This sensor is being addressed
	#if (SENSOR_12_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_12_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_12:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_13_PRESENT
	movfw packet7
	xorlw 13
	btfss STATUS,Z
	goto notthissensor_13
	; This sensor is being addressed
	#if (SENSOR_13_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_13_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_13:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_14_PRESENT
	movfw packet7
	xorlw 14
	btfss STATUS,Z
	goto notthissensor_14
	; This sensor is being addressed
	#if (SENSOR_14_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_14_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_14:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_15_PRESENT
	movfw packet7
	xorlw 15
	btfss STATUS,Z
	goto notthissensor_15
	; This sensor is being addressed
	#if (SENSOR_15_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_15_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_15:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_16_PRESENT
	movfw packet7
	xorlw 16
	btfss STATUS,Z
	goto notthissensor_16
	; This sensor is being addressed
	#if (SENSOR_16_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_16_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_16:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_17_PRESENT
	movfw packet7
	xorlw 17
	btfss STATUS,Z
	goto notthissensor_17
	; This sensor is being addressed
	#if (SENSOR_17_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_17_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_17:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_18_PRESENT
	movfw packet7
	xorlw 18
	btfss STATUS,Z
	goto notthissensor_18
	; This sensor is being addressed
	#if (SENSOR_18_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_18_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_18:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_19_PRESENT
	movfw packet7
	xorlw 19
	btfss STATUS,Z
	goto notthissensor_19
	; This sensor is being addressed
	#if (SENSOR_19_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_19_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_19:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_20_PRESENT
	movfw packet7
	xorlw 20
	btfss STATUS,Z
	goto notthissensor_20
	; This sensor is being addressed
	#if (SENSOR_20_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_20_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_20:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_21_PRESENT
	movfw packet7
	xorlw 21
	btfss STATUS,Z
	goto notthissensor_21
	; This sensor is being addressed
	#if (SENSOR_21_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_21_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_21:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_22_PRESENT
	movfw packet7
	xorlw 22
	btfss STATUS,Z
	goto notthissensor_22
	; This sensor is being addressed
	#if (SENSOR_22_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_22_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_22:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_23_PRESENT
	movfw packet7
	xorlw 23
	btfss STATUS,Z
	goto notthissensor_23
	; This sensor is being addressed
	#if (SENSOR_23_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_23_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_23:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_24_PRESENT
	movfw packet7
	xorlw 24
	btfss STATUS,Z
	goto notthissensor_24
	; This sensor is being addressed
	#if (SENSOR_24_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_24_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_24:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_25_PRESENT
	movfw packet7
	xorlw 25
	btfss STATUS,Z
	goto notthissensor_25
	; This sensor is being addressed
	#if (SENSOR_25_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_25_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_25:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_26_PRESENT
	movfw packet7
	xorlw 26
	btfss STATUS,Z
	goto notthissensor_26
	; This sensor is being addressed
	#if (SENSOR_26_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_26_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_26:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_27_PRESENT
	movfw packet7
	xorlw 27
	btfss STATUS,Z
	goto notthissensor_27
	; This sensor is being addressed
	#if (SENSOR_27_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_27_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_27:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_28_PRESENT
	movfw packet7
	xorlw 28
	btfss STATUS,Z
	goto notthissensor_28
	; This sensor is being addressed
	#if (SENSOR_28_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_28_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_28:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_29_PRESENT
	movfw packet7
	xorlw 29
	btfss STATUS,Z
	goto notthissensor_29
	; This sensor is being addressed
	#if (SENSOR_29_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_29_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_29:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_30_PRESENT
	movfw packet7
	xorlw 30
	btfss STATUS,Z
	goto notthissensor_30
	; This sensor is being addressed
	#if (SENSOR_30_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_30_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_30:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_31_PRESENT
	movfw packet7
	xorlw 31
	btfss STATUS,Z
	goto notthissensor_31
	; This sensor is being addressed
	#if (SENSOR_31_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_31_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_31:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_32_PRESENT
	movfw packet7
	xorlw 32
	btfss STATUS,Z
	goto notthissensor_32
	; This sensor is being addressed
	#if (SENSOR_32_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_32_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_32:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_33_PRESENT
	movfw packet7
	xorlw 33
	btfss STATUS,Z
	goto notthissensor_33
	; This sensor is being addressed
	#if (SENSOR_33_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_33_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_33:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_34_PRESENT
	movfw packet7
	xorlw 34
	btfss STATUS,Z
	goto notthissensor_34
	; This sensor is being addressed
	#if (SENSOR_34_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_34_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_34:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_35_PRESENT
	movfw packet7
	xorlw 35
	btfss STATUS,Z
	goto notthissensor_35
	; This sensor is being addressed
	#if (SENSOR_35_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_35_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_35:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_36_PRESENT
	movfw packet7
	xorlw 36
	btfss STATUS,Z
	goto notthissensor_36
	; This sensor is being addressed
	#if (SENSOR_36_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_36_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_36:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_37_PRESENT
	movfw packet7
	xorlw 37
	btfss STATUS,Z
	goto notthissensor_37
	; This sensor is being addressed
	#if (SENSOR_37_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_37_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_37:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_38_PRESENT
	movfw packet7
	xorlw 38
	btfss STATUS,Z
	goto notthissensor_38
	; This sensor is being addressed
	#if (SENSOR_38_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_38_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_38:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_39_PRESENT
	movfw packet7
	xorlw 39
	btfss STATUS,Z
	goto notthissensor_39
	; This sensor is being addressed
	#if (SENSOR_39_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_39_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_39:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_40_PRESENT
	movfw packet7
	xorlw 40
	btfss STATUS,Z
	goto notthissensor_40
	; This sensor is being addressed
	#if (SENSOR_40_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_40_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_40:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_41_PRESENT
	movfw packet7
	xorlw 41
	btfss STATUS,Z
	goto notthissensor_41
	; This sensor is being addressed
	#if (SENSOR_41_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_41_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_41:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_42_PRESENT
	movfw packet7
	xorlw 42
	btfss STATUS,Z
	goto notthissensor_42
	; This sensor is being addressed
	#if (SENSOR_42_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_42_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_42:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_43_PRESENT
	movfw packet7
	xorlw 43
	btfss STATUS,Z
	goto notthissensor_43
	; This sensor is being addressed
	#if (SENSOR_43_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_43_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_43:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_44_PRESENT
	movfw packet7
	xorlw 44
	btfss STATUS,Z
	goto notthissensor_44
	; This sensor is being addressed
	#if (SENSOR_44_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_44_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_44:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_45_PRESENT
	movfw packet7
	xorlw 45
	btfss STATUS,Z
	goto notthissensor_45
	; This sensor is being addressed
	#if (SENSOR_45_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_45_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_45:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_46_PRESENT
	movfw packet7
	xorlw 46
	btfss STATUS,Z
	goto notthissensor_46
	; This sensor is being addressed
	#if (SENSOR_46_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_46_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_46:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_47_PRESENT
	movfw packet7
	xorlw 47
	btfss STATUS,Z
	goto notthissensor_47
	; This sensor is being addressed
	#if (SENSOR_47_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_47_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_47:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_48_PRESENT
	movfw packet7
	xorlw 48
	btfss STATUS,Z
	goto notthissensor_48
	; This sensor is being addressed
	#if (SENSOR_48_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_48_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_48:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_49_PRESENT
	movfw packet7
	xorlw 49
	btfss STATUS,Z
	goto notthissensor_49
	; This sensor is being addressed
	#if (SENSOR_49_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_49_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_49:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_50_PRESENT
	movfw packet7
	xorlw 50
	btfss STATUS,Z
	goto notthissensor_50
	; This sensor is being addressed
	#if (SENSOR_50_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_50_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_50:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_51_PRESENT
	movfw packet7
	xorlw 51
	btfss STATUS,Z
	goto notthissensor_51
	; This sensor is being addressed
	#if (SENSOR_51_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_51_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_51:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_52_PRESENT
	movfw packet7
	xorlw 52
	btfss STATUS,Z
	goto notthissensor_52
	; This sensor is being addressed
	#if (SENSOR_52_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_52_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_52:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_53_PRESENT
	movfw packet7
	xorlw 53
	btfss STATUS,Z
	goto notthissensor_53
	; This sensor is being addressed
	#if (SENSOR_53_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_53_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_53:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_54_PRESENT
	movfw packet7
	xorlw 54
	btfss STATUS,Z
	goto notthissensor_54
	; This sensor is being addressed
	#if (SENSOR_54_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_54_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_54:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_55_PRESENT
	movfw packet7
	xorlw 55
	btfss STATUS,Z
	goto notthissensor_55
	; This sensor is being addressed
	#if (SENSOR_55_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_55_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_55:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_56_PRESENT
	movfw packet7
	xorlw 56
	btfss STATUS,Z
	goto notthissensor_56
	; This sensor is being addressed
	#if (SENSOR_56_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_56_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_56:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_57_PRESENT
	movfw packet7
	xorlw 57
	btfss STATUS,Z
	goto notthissensor_57
	; This sensor is being addressed
	#if (SENSOR_57_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_57_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_57:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_58_PRESENT
	movfw packet7
	xorlw 58
	btfss STATUS,Z
	goto notthissensor_58
	; This sensor is being addressed
	#if (SENSOR_58_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_58_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_58:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_59_PRESENT
	movfw packet7
	xorlw 59
	btfss STATUS,Z
	goto notthissensor_59
	; This sensor is being addressed
	#if (SENSOR_59_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_59_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_59:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_60_PRESENT
	movfw packet7
	xorlw 60
	btfss STATUS,Z
	goto notthissensor_60
	; This sensor is being addressed
	#if (SENSOR_60_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_60_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_60:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_61_PRESENT
	movfw packet7
	xorlw 61
	btfss STATUS,Z
	goto notthissensor_61
	; This sensor is being addressed
	#if (SENSOR_61_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_61_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_61:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_62_PRESENT
	movfw packet7
	xorlw 62
	btfss STATUS,Z
	goto notthissensor_62
	; This sensor is being addressed
	#if (SENSOR_62_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_62_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_62:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_63_PRESENT
	movfw packet7
	xorlw 63
	btfss STATUS,Z
	goto notthissensor_63
	; This sensor is being addressed
	#if (SENSOR_63_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_63_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_63:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_64_PRESENT
	movfw packet7
	xorlw 64
	btfss STATUS,Z
	goto notthissensor_64
	; This sensor is being addressed
	#if (SENSOR_64_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_64_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_64:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_65_PRESENT
	movfw packet7
	xorlw 65
	btfss STATUS,Z
	goto notthissensor_65
	; This sensor is being addressed
	#if (SENSOR_65_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_65_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_65:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_66_PRESENT
	movfw packet7
	xorlw 66
	btfss STATUS,Z
	goto notthissensor_66
	; This sensor is being addressed
	#if (SENSOR_66_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_66_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_66:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_67_PRESENT
	movfw packet7
	xorlw 67
	btfss STATUS,Z
	goto notthissensor_67
	; This sensor is being addressed
	#if (SENSOR_67_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_67_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_67:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_68_PRESENT
	movfw packet7
	xorlw 68
	btfss STATUS,Z
	goto notthissensor_68
	; This sensor is being addressed
	#if (SENSOR_68_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_68_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_68:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_69_PRESENT
	movfw packet7
	xorlw 69
	btfss STATUS,Z
	goto notthissensor_69
	; This sensor is being addressed
	#if (SENSOR_69_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_69_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_69:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_70_PRESENT
	movfw packet7
	xorlw 70
	btfss STATUS,Z
	goto notthissensor_70
	; This sensor is being addressed
	#if (SENSOR_70_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_70_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_70:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_71_PRESENT
	movfw packet7
	xorlw 71
	btfss STATUS,Z
	goto notthissensor_71
	; This sensor is being addressed
	#if (SENSOR_71_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_71_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_71:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_72_PRESENT
	movfw packet7
	xorlw 72
	btfss STATUS,Z
	goto notthissensor_72
	; This sensor is being addressed
	#if (SENSOR_72_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_72_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_72:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_73_PRESENT
	movfw packet7
	xorlw 73
	btfss STATUS,Z
	goto notthissensor_73
	; This sensor is being addressed
	#if (SENSOR_73_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_73_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_73:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_74_PRESENT
	movfw packet7
	xorlw 74
	btfss STATUS,Z
	goto notthissensor_74
	; This sensor is being addressed
	#if (SENSOR_74_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_74_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_74:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_75_PRESENT
	movfw packet7
	xorlw 75
	btfss STATUS,Z
	goto notthissensor_75
	; This sensor is being addressed
	#if (SENSOR_75_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_75_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_75:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_76_PRESENT
	movfw packet7
	xorlw 76
	btfss STATUS,Z
	goto notthissensor_76
	; This sensor is being addressed
	#if (SENSOR_76_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_76_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_76:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_77_PRESENT
	movfw packet7
	xorlw 77
	btfss STATUS,Z
	goto notthissensor_77
	; This sensor is being addressed
	#if (SENSOR_77_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_77_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_77:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_78_PRESENT
	movfw packet7
	xorlw 78
	btfss STATUS,Z
	goto notthissensor_78
	; This sensor is being addressed
	#if (SENSOR_78_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_78_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_78:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_79_PRESENT
	movfw packet7
	xorlw 79
	btfss STATUS,Z
	goto notthissensor_79
	; This sensor is being addressed
	#if (SENSOR_79_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_79_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_79:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_80_PRESENT
	movfw packet7
	xorlw 80
	btfss STATUS,Z
	goto notthissensor_80
	; This sensor is being addressed
	#if (SENSOR_80_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_80_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_80:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_81_PRESENT
	movfw packet7
	xorlw 81
	btfss STATUS,Z
	goto notthissensor_81
	; This sensor is being addressed
	#if (SENSOR_81_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_81_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_81:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_82_PRESENT
	movfw packet7
	xorlw 82
	btfss STATUS,Z
	goto notthissensor_82
	; This sensor is being addressed
	#if (SENSOR_82_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_82_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_82:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_83_PRESENT
	movfw packet7
	xorlw 83
	btfss STATUS,Z
	goto notthissensor_83
	; This sensor is being addressed
	#if (SENSOR_83_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_83_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_83:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_84_PRESENT
	movfw packet7
	xorlw 84
	btfss STATUS,Z
	goto notthissensor_84
	; This sensor is being addressed
	#if (SENSOR_84_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_84_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_84:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_85_PRESENT
	movfw packet7
	xorlw 85
	btfss STATUS,Z
	goto notthissensor_85
	; This sensor is being addressed
	#if (SENSOR_85_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_85_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_85:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_86_PRESENT
	movfw packet7
	xorlw 86
	btfss STATUS,Z
	goto notthissensor_86
	; This sensor is being addressed
	#if (SENSOR_86_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_86_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_86:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_87_PRESENT
	movfw packet7
	xorlw 87
	btfss STATUS,Z
	goto notthissensor_87
	; This sensor is being addressed
	#if (SENSOR_87_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_87_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_87:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_88_PRESENT
	movfw packet7
	xorlw 88
	btfss STATUS,Z
	goto notthissensor_88
	; This sensor is being addressed
	#if (SENSOR_88_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_88_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_88:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_89_PRESENT
	movfw packet7
	xorlw 89
	btfss STATUS,Z
	goto notthissensor_89
	; This sensor is being addressed
	#if (SENSOR_89_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_89_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_89:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_90_PRESENT
	movfw packet7
	xorlw 90
	btfss STATUS,Z
	goto notthissensor_90
	; This sensor is being addressed
	#if (SENSOR_90_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_90_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_90:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_91_PRESENT
	movfw packet7
	xorlw 91
	btfss STATUS,Z
	goto notthissensor_91
	; This sensor is being addressed
	#if (SENSOR_91_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_91_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_91:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_92_PRESENT
	movfw packet7
	xorlw 92
	btfss STATUS,Z
	goto notthissensor_92
	; This sensor is being addressed
	#if (SENSOR_92_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_92_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_92:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_93_PRESENT
	movfw packet7
	xorlw 93
	btfss STATUS,Z
	goto notthissensor_93
	; This sensor is being addressed
	#if (SENSOR_93_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_93_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_93:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_94_PRESENT
	movfw packet7
	xorlw 94
	btfss STATUS,Z
	goto notthissensor_94
	; This sensor is being addressed
	#if (SENSOR_94_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_94_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_94:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_95_PRESENT
	movfw packet7
	xorlw 95
	btfss STATUS,Z
	goto notthissensor_95
	; This sensor is being addressed
	#if (SENSOR_95_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_95_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_95:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_96_PRESENT
	movfw packet7
	xorlw 96
	btfss STATUS,Z
	goto notthissensor_96
	; This sensor is being addressed
	#if (SENSOR_96_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_96_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_96:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_97_PRESENT
	movfw packet7
	xorlw 97
	btfss STATUS,Z
	goto notthissensor_97
	; This sensor is being addressed
	#if (SENSOR_97_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_97_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_97:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_98_PRESENT
	movfw packet7
	xorlw 98
	btfss STATUS,Z
	goto notthissensor_98
	; This sensor is being addressed
	#if (SENSOR_98_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_98_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_98:  
	; OK, skip to the next sensor.
#endif
#ifdef SENSOR_99_PRESENT
	movfw packet7
	xorlw 99
	btfss STATUS,Z
	goto notthissensor_99
	; This sensor is being addressed
	#if (SENSOR_99_TYPE == SENSOR_ID_GENERIC_DIGITAL_OUT)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_OUT 
	#endif
	#if (SENSOR_99_TYPE == SENSOR_ID_GENERIC_DIGITAL_IN)	
	  movlw SENSOR_ID_GENERIC_DIGITAL_IN 
	#endif
	; Jump to the end of the autogenned code so we don't have to check every other
	; sensor, too.
	goto returnOK

notthissensor_99:  
	; OK, skip to the next sensor.
#endif
returnOK:
	clrf packet5
	movwf packet7

	return

	sensor_not_found:

	movlw 0x80
	movwf packet5
	movlw ERR_GET_SENSOR_TYPE_NODE_NOT_FND
	movwf packet7

	return

end