; ************************************************ 
; **         THIS FILE IS AUTOGENERATED!        ** 
; ** YOU PROBABLY REALLY DON'T WANT TO EDIT IT! ** 
; ************************************************ 
; Source: template_cmd-set-sensor.asm

	#include "main.h"
	#include "sensorcfg.h"
	#include "processnamedcmd.asm"
	#include "debugger.h"
	#include "protocol.h"

	errorlevel  -302  

	CODE
do_cmd_set_sensor
	GLOBAL do_cmd_set_sensor

	; This command takes one byte of sensor ID, in packet7,
	; and one byte of state data in packet6.The sensor will
	; respond with 0x00000000 on success, or report the
	; error in packet7 on failure.
	; It is expected that output sensors add to this command
	; rather than create a new command.

	movlw DEBUGGER_GOT_CMD_SETSENSOR
	call debugger_spitvalue;

	; Now, work out what is selected. 

#ifdef SENSOR_0_PRESENT
	movfw packet7
	xorlw h'0'
	btfsc STATUS,Z
	goto cmd_set_sensor_0	; sensor 1 is selected
#endif
#ifdef SENSOR_1_PRESENT
	movfw packet7
	xorlw h'1'
	btfsc STATUS,Z
	goto cmd_set_sensor_1	; sensor 1 is selected
#endif
#ifdef SENSOR_2_PRESENT
	movfw packet7
	xorlw h'2'
	btfsc STATUS,Z
	goto cmd_set_sensor_2	; sensor 1 is selected
#endif
#ifdef SENSOR_3_PRESENT
	movfw packet7
	xorlw h'3'
	btfsc STATUS,Z
	goto cmd_set_sensor_3	; sensor 1 is selected
#endif
#ifdef SENSOR_4_PRESENT
	movfw packet7
	xorlw h'4'
	btfsc STATUS,Z
	goto cmd_set_sensor_4	; sensor 1 is selected
#endif
#ifdef SENSOR_5_PRESENT
	movfw packet7
	xorlw h'5'
	btfsc STATUS,Z
	goto cmd_set_sensor_5	; sensor 1 is selected
#endif
#ifdef SENSOR_6_PRESENT
	movfw packet7
	xorlw h'6'
	btfsc STATUS,Z
	goto cmd_set_sensor_6	; sensor 1 is selected
#endif
#ifdef SENSOR_7_PRESENT
	movfw packet7
	xorlw h'7'
	btfsc STATUS,Z
	goto cmd_set_sensor_7	; sensor 1 is selected
#endif
#ifdef SENSOR_8_PRESENT
	movfw packet7
	xorlw h'8'
	btfsc STATUS,Z
	goto cmd_set_sensor_8	; sensor 1 is selected
#endif
#ifdef SENSOR_9_PRESENT
	movfw packet7
	xorlw h'9'
	btfsc STATUS,Z
	goto cmd_set_sensor_9	; sensor 1 is selected
#endif
#ifdef SENSOR_10_PRESENT
	movfw packet7
	xorlw h'10'
	btfsc STATUS,Z
	goto cmd_set_sensor_10	; sensor 1 is selected
#endif
#ifdef SENSOR_11_PRESENT
	movfw packet7
	xorlw h'11'
	btfsc STATUS,Z
	goto cmd_set_sensor_11	; sensor 1 is selected
#endif
#ifdef SENSOR_12_PRESENT
	movfw packet7
	xorlw h'12'
	btfsc STATUS,Z
	goto cmd_set_sensor_12	; sensor 1 is selected
#endif
#ifdef SENSOR_13_PRESENT
	movfw packet7
	xorlw h'13'
	btfsc STATUS,Z
	goto cmd_set_sensor_13	; sensor 1 is selected
#endif
#ifdef SENSOR_14_PRESENT
	movfw packet7
	xorlw h'14'
	btfsc STATUS,Z
	goto cmd_set_sensor_14	; sensor 1 is selected
#endif
#ifdef SENSOR_15_PRESENT
	movfw packet7
	xorlw h'15'
	btfsc STATUS,Z
	goto cmd_set_sensor_15	; sensor 1 is selected
#endif
#ifdef SENSOR_16_PRESENT
	movfw packet7
	xorlw h'16'
	btfsc STATUS,Z
	goto cmd_set_sensor_16	; sensor 1 is selected
#endif
#ifdef SENSOR_17_PRESENT
	movfw packet7
	xorlw h'17'
	btfsc STATUS,Z
	goto cmd_set_sensor_17	; sensor 1 is selected
#endif
#ifdef SENSOR_18_PRESENT
	movfw packet7
	xorlw h'18'
	btfsc STATUS,Z
	goto cmd_set_sensor_18	; sensor 1 is selected
#endif
#ifdef SENSOR_19_PRESENT
	movfw packet7
	xorlw h'19'
	btfsc STATUS,Z
	goto cmd_set_sensor_19	; sensor 1 is selected
#endif
#ifdef SENSOR_20_PRESENT
	movfw packet7
	xorlw h'20'
	btfsc STATUS,Z
	goto cmd_set_sensor_20	; sensor 1 is selected
#endif
#ifdef SENSOR_21_PRESENT
	movfw packet7
	xorlw h'21'
	btfsc STATUS,Z
	goto cmd_set_sensor_21	; sensor 1 is selected
#endif
#ifdef SENSOR_22_PRESENT
	movfw packet7
	xorlw h'22'
	btfsc STATUS,Z
	goto cmd_set_sensor_22	; sensor 1 is selected
#endif
#ifdef SENSOR_23_PRESENT
	movfw packet7
	xorlw h'23'
	btfsc STATUS,Z
	goto cmd_set_sensor_23	; sensor 1 is selected
#endif
#ifdef SENSOR_24_PRESENT
	movfw packet7
	xorlw h'24'
	btfsc STATUS,Z
	goto cmd_set_sensor_24	; sensor 1 is selected
#endif
#ifdef SENSOR_25_PRESENT
	movfw packet7
	xorlw h'25'
	btfsc STATUS,Z
	goto cmd_set_sensor_25	; sensor 1 is selected
#endif
#ifdef SENSOR_26_PRESENT
	movfw packet7
	xorlw h'26'
	btfsc STATUS,Z
	goto cmd_set_sensor_26	; sensor 1 is selected
#endif
#ifdef SENSOR_27_PRESENT
	movfw packet7
	xorlw h'27'
	btfsc STATUS,Z
	goto cmd_set_sensor_27	; sensor 1 is selected
#endif
#ifdef SENSOR_28_PRESENT
	movfw packet7
	xorlw h'28'
	btfsc STATUS,Z
	goto cmd_set_sensor_28	; sensor 1 is selected
#endif
#ifdef SENSOR_29_PRESENT
	movfw packet7
	xorlw h'29'
	btfsc STATUS,Z
	goto cmd_set_sensor_29	; sensor 1 is selected
#endif
#ifdef SENSOR_30_PRESENT
	movfw packet7
	xorlw h'30'
	btfsc STATUS,Z
	goto cmd_set_sensor_30	; sensor 1 is selected
#endif
#ifdef SENSOR_31_PRESENT
	movfw packet7
	xorlw h'31'
	btfsc STATUS,Z
	goto cmd_set_sensor_31	; sensor 1 is selected
#endif
#ifdef SENSOR_32_PRESENT
	movfw packet7
	xorlw h'32'
	btfsc STATUS,Z
	goto cmd_set_sensor_32	; sensor 1 is selected
#endif
#ifdef SENSOR_33_PRESENT
	movfw packet7
	xorlw h'33'
	btfsc STATUS,Z
	goto cmd_set_sensor_33	; sensor 1 is selected
#endif
#ifdef SENSOR_34_PRESENT
	movfw packet7
	xorlw h'34'
	btfsc STATUS,Z
	goto cmd_set_sensor_34	; sensor 1 is selected
#endif
#ifdef SENSOR_35_PRESENT
	movfw packet7
	xorlw h'35'
	btfsc STATUS,Z
	goto cmd_set_sensor_35	; sensor 1 is selected
#endif
#ifdef SENSOR_36_PRESENT
	movfw packet7
	xorlw h'36'
	btfsc STATUS,Z
	goto cmd_set_sensor_36	; sensor 1 is selected
#endif
#ifdef SENSOR_37_PRESENT
	movfw packet7
	xorlw h'37'
	btfsc STATUS,Z
	goto cmd_set_sensor_37	; sensor 1 is selected
#endif
#ifdef SENSOR_38_PRESENT
	movfw packet7
	xorlw h'38'
	btfsc STATUS,Z
	goto cmd_set_sensor_38	; sensor 1 is selected
#endif
#ifdef SENSOR_39_PRESENT
	movfw packet7
	xorlw h'39'
	btfsc STATUS,Z
	goto cmd_set_sensor_39	; sensor 1 is selected
#endif
#ifdef SENSOR_40_PRESENT
	movfw packet7
	xorlw h'40'
	btfsc STATUS,Z
	goto cmd_set_sensor_40	; sensor 1 is selected
#endif
#ifdef SENSOR_41_PRESENT
	movfw packet7
	xorlw h'41'
	btfsc STATUS,Z
	goto cmd_set_sensor_41	; sensor 1 is selected
#endif
#ifdef SENSOR_42_PRESENT
	movfw packet7
	xorlw h'42'
	btfsc STATUS,Z
	goto cmd_set_sensor_42	; sensor 1 is selected
#endif
#ifdef SENSOR_43_PRESENT
	movfw packet7
	xorlw h'43'
	btfsc STATUS,Z
	goto cmd_set_sensor_43	; sensor 1 is selected
#endif
#ifdef SENSOR_44_PRESENT
	movfw packet7
	xorlw h'44'
	btfsc STATUS,Z
	goto cmd_set_sensor_44	; sensor 1 is selected
#endif
#ifdef SENSOR_45_PRESENT
	movfw packet7
	xorlw h'45'
	btfsc STATUS,Z
	goto cmd_set_sensor_45	; sensor 1 is selected
#endif
#ifdef SENSOR_46_PRESENT
	movfw packet7
	xorlw h'46'
	btfsc STATUS,Z
	goto cmd_set_sensor_46	; sensor 1 is selected
#endif
#ifdef SENSOR_47_PRESENT
	movfw packet7
	xorlw h'47'
	btfsc STATUS,Z
	goto cmd_set_sensor_47	; sensor 1 is selected
#endif
#ifdef SENSOR_48_PRESENT
	movfw packet7
	xorlw h'48'
	btfsc STATUS,Z
	goto cmd_set_sensor_48	; sensor 1 is selected
#endif
#ifdef SENSOR_49_PRESENT
	movfw packet7
	xorlw h'49'
	btfsc STATUS,Z
	goto cmd_set_sensor_49	; sensor 1 is selected
#endif
#ifdef SENSOR_50_PRESENT
	movfw packet7
	xorlw h'50'
	btfsc STATUS,Z
	goto cmd_set_sensor_50	; sensor 1 is selected
#endif
#ifdef SENSOR_51_PRESENT
	movfw packet7
	xorlw h'51'
	btfsc STATUS,Z
	goto cmd_set_sensor_51	; sensor 1 is selected
#endif
#ifdef SENSOR_52_PRESENT
	movfw packet7
	xorlw h'52'
	btfsc STATUS,Z
	goto cmd_set_sensor_52	; sensor 1 is selected
#endif
#ifdef SENSOR_53_PRESENT
	movfw packet7
	xorlw h'53'
	btfsc STATUS,Z
	goto cmd_set_sensor_53	; sensor 1 is selected
#endif
#ifdef SENSOR_54_PRESENT
	movfw packet7
	xorlw h'54'
	btfsc STATUS,Z
	goto cmd_set_sensor_54	; sensor 1 is selected
#endif
#ifdef SENSOR_55_PRESENT
	movfw packet7
	xorlw h'55'
	btfsc STATUS,Z
	goto cmd_set_sensor_55	; sensor 1 is selected
#endif
#ifdef SENSOR_56_PRESENT
	movfw packet7
	xorlw h'56'
	btfsc STATUS,Z
	goto cmd_set_sensor_56	; sensor 1 is selected
#endif
#ifdef SENSOR_57_PRESENT
	movfw packet7
	xorlw h'57'
	btfsc STATUS,Z
	goto cmd_set_sensor_57	; sensor 1 is selected
#endif
#ifdef SENSOR_58_PRESENT
	movfw packet7
	xorlw h'58'
	btfsc STATUS,Z
	goto cmd_set_sensor_58	; sensor 1 is selected
#endif
#ifdef SENSOR_59_PRESENT
	movfw packet7
	xorlw h'59'
	btfsc STATUS,Z
	goto cmd_set_sensor_59	; sensor 1 is selected
#endif
#ifdef SENSOR_60_PRESENT
	movfw packet7
	xorlw h'60'
	btfsc STATUS,Z
	goto cmd_set_sensor_60	; sensor 1 is selected
#endif
#ifdef SENSOR_61_PRESENT
	movfw packet7
	xorlw h'61'
	btfsc STATUS,Z
	goto cmd_set_sensor_61	; sensor 1 is selected
#endif
#ifdef SENSOR_62_PRESENT
	movfw packet7
	xorlw h'62'
	btfsc STATUS,Z
	goto cmd_set_sensor_62	; sensor 1 is selected
#endif
#ifdef SENSOR_63_PRESENT
	movfw packet7
	xorlw h'63'
	btfsc STATUS,Z
	goto cmd_set_sensor_63	; sensor 1 is selected
#endif
#ifdef SENSOR_64_PRESENT
	movfw packet7
	xorlw h'64'
	btfsc STATUS,Z
	goto cmd_set_sensor_64	; sensor 1 is selected
#endif
#ifdef SENSOR_65_PRESENT
	movfw packet7
	xorlw h'65'
	btfsc STATUS,Z
	goto cmd_set_sensor_65	; sensor 1 is selected
#endif
#ifdef SENSOR_66_PRESENT
	movfw packet7
	xorlw h'66'
	btfsc STATUS,Z
	goto cmd_set_sensor_66	; sensor 1 is selected
#endif
#ifdef SENSOR_67_PRESENT
	movfw packet7
	xorlw h'67'
	btfsc STATUS,Z
	goto cmd_set_sensor_67	; sensor 1 is selected
#endif
#ifdef SENSOR_68_PRESENT
	movfw packet7
	xorlw h'68'
	btfsc STATUS,Z
	goto cmd_set_sensor_68	; sensor 1 is selected
#endif
#ifdef SENSOR_69_PRESENT
	movfw packet7
	xorlw h'69'
	btfsc STATUS,Z
	goto cmd_set_sensor_69	; sensor 1 is selected
#endif
#ifdef SENSOR_70_PRESENT
	movfw packet7
	xorlw h'70'
	btfsc STATUS,Z
	goto cmd_set_sensor_70	; sensor 1 is selected
#endif
#ifdef SENSOR_71_PRESENT
	movfw packet7
	xorlw h'71'
	btfsc STATUS,Z
	goto cmd_set_sensor_71	; sensor 1 is selected
#endif
#ifdef SENSOR_72_PRESENT
	movfw packet7
	xorlw h'72'
	btfsc STATUS,Z
	goto cmd_set_sensor_72	; sensor 1 is selected
#endif
#ifdef SENSOR_73_PRESENT
	movfw packet7
	xorlw h'73'
	btfsc STATUS,Z
	goto cmd_set_sensor_73	; sensor 1 is selected
#endif
#ifdef SENSOR_74_PRESENT
	movfw packet7
	xorlw h'74'
	btfsc STATUS,Z
	goto cmd_set_sensor_74	; sensor 1 is selected
#endif
#ifdef SENSOR_75_PRESENT
	movfw packet7
	xorlw h'75'
	btfsc STATUS,Z
	goto cmd_set_sensor_75	; sensor 1 is selected
#endif
#ifdef SENSOR_76_PRESENT
	movfw packet7
	xorlw h'76'
	btfsc STATUS,Z
	goto cmd_set_sensor_76	; sensor 1 is selected
#endif
#ifdef SENSOR_77_PRESENT
	movfw packet7
	xorlw h'77'
	btfsc STATUS,Z
	goto cmd_set_sensor_77	; sensor 1 is selected
#endif
#ifdef SENSOR_78_PRESENT
	movfw packet7
	xorlw h'78'
	btfsc STATUS,Z
	goto cmd_set_sensor_78	; sensor 1 is selected
#endif
#ifdef SENSOR_79_PRESENT
	movfw packet7
	xorlw h'79'
	btfsc STATUS,Z
	goto cmd_set_sensor_79	; sensor 1 is selected
#endif
#ifdef SENSOR_80_PRESENT
	movfw packet7
	xorlw h'80'
	btfsc STATUS,Z
	goto cmd_set_sensor_80	; sensor 1 is selected
#endif
#ifdef SENSOR_81_PRESENT
	movfw packet7
	xorlw h'81'
	btfsc STATUS,Z
	goto cmd_set_sensor_81	; sensor 1 is selected
#endif
#ifdef SENSOR_82_PRESENT
	movfw packet7
	xorlw h'82'
	btfsc STATUS,Z
	goto cmd_set_sensor_82	; sensor 1 is selected
#endif
#ifdef SENSOR_83_PRESENT
	movfw packet7
	xorlw h'83'
	btfsc STATUS,Z
	goto cmd_set_sensor_83	; sensor 1 is selected
#endif
#ifdef SENSOR_84_PRESENT
	movfw packet7
	xorlw h'84'
	btfsc STATUS,Z
	goto cmd_set_sensor_84	; sensor 1 is selected
#endif
#ifdef SENSOR_85_PRESENT
	movfw packet7
	xorlw h'85'
	btfsc STATUS,Z
	goto cmd_set_sensor_85	; sensor 1 is selected
#endif
#ifdef SENSOR_86_PRESENT
	movfw packet7
	xorlw h'86'
	btfsc STATUS,Z
	goto cmd_set_sensor_86	; sensor 1 is selected
#endif
#ifdef SENSOR_87_PRESENT
	movfw packet7
	xorlw h'87'
	btfsc STATUS,Z
	goto cmd_set_sensor_87	; sensor 1 is selected
#endif
#ifdef SENSOR_88_PRESENT
	movfw packet7
	xorlw h'88'
	btfsc STATUS,Z
	goto cmd_set_sensor_88	; sensor 1 is selected
#endif
#ifdef SENSOR_89_PRESENT
	movfw packet7
	xorlw h'89'
	btfsc STATUS,Z
	goto cmd_set_sensor_89	; sensor 1 is selected
#endif
#ifdef SENSOR_90_PRESENT
	movfw packet7
	xorlw h'90'
	btfsc STATUS,Z
	goto cmd_set_sensor_90	; sensor 1 is selected
#endif
#ifdef SENSOR_91_PRESENT
	movfw packet7
	xorlw h'91'
	btfsc STATUS,Z
	goto cmd_set_sensor_91	; sensor 1 is selected
#endif
#ifdef SENSOR_92_PRESENT
	movfw packet7
	xorlw h'92'
	btfsc STATUS,Z
	goto cmd_set_sensor_92	; sensor 1 is selected
#endif
#ifdef SENSOR_93_PRESENT
	movfw packet7
	xorlw h'93'
	btfsc STATUS,Z
	goto cmd_set_sensor_93	; sensor 1 is selected
#endif
#ifdef SENSOR_94_PRESENT
	movfw packet7
	xorlw h'94'
	btfsc STATUS,Z
	goto cmd_set_sensor_94	; sensor 1 is selected
#endif
#ifdef SENSOR_95_PRESENT
	movfw packet7
	xorlw h'95'
	btfsc STATUS,Z
	goto cmd_set_sensor_95	; sensor 1 is selected
#endif
#ifdef SENSOR_96_PRESENT
	movfw packet7
	xorlw h'96'
	btfsc STATUS,Z
	goto cmd_set_sensor_96	; sensor 1 is selected
#endif
#ifdef SENSOR_97_PRESENT
	movfw packet7
	xorlw h'97'
	btfsc STATUS,Z
	goto cmd_set_sensor_97	; sensor 1 is selected
#endif
#ifdef SENSOR_98_PRESENT
	movfw packet7
	xorlw h'98'
	btfsc STATUS,Z
	goto cmd_set_sensor_98	; sensor 1 is selected
#endif
#ifdef SENSOR_99_PRESENT
	movfw packet7
	xorlw h'99'
	btfsc STATUS,Z
	goto cmd_set_sensor_99	; sensor 1 is selected
#endif
	movlw DEBUGGER_UNKNOWN_SENSOR
	call debugger_spitvalue;

	; don't know this sensor! respond with a failure indicator.
	clrf packet4
	clrf packet5
	clrf packet6
	movlw ERR_SET_SENSOR_NODE_NOT_FOUND
	movwf packet7
	return

;
; If you are creating a new sensor type, add a test here in the form of
;  #if (SENSOR_ID_<your identifier> == SENSOR_(AUTOGEN_EVERY_SENSOR_ID)_TYPE)
;    (driver code for sensor (AUTOGEN_EVERY_SENSOR_ID))
;  #endif
;
#ifdef SENSOR_0_PRESENT
cmd_set_sensor_0:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_0_TYPE)
		btfss packet6, 0
		goto cmd_set_0_is_clear
		bsf SENSOR_0_PORT, SENSOR_0_PIN
		goto cmd_set_return_ok
cmd_set_0_is_clear:
		bcf SENSOR_0_PORT, SENSOR_0_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_1_PRESENT
cmd_set_sensor_1:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_1_TYPE)
		btfss packet6, 0
		goto cmd_set_1_is_clear
		bsf SENSOR_1_PORT, SENSOR_1_PIN
		goto cmd_set_return_ok
cmd_set_1_is_clear:
		bcf SENSOR_1_PORT, SENSOR_1_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_2_PRESENT
cmd_set_sensor_2:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_2_TYPE)
		btfss packet6, 0
		goto cmd_set_2_is_clear
		bsf SENSOR_2_PORT, SENSOR_2_PIN
		goto cmd_set_return_ok
cmd_set_2_is_clear:
		bcf SENSOR_2_PORT, SENSOR_2_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_3_PRESENT
cmd_set_sensor_3:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_3_TYPE)
		btfss packet6, 0
		goto cmd_set_3_is_clear
		bsf SENSOR_3_PORT, SENSOR_3_PIN
		goto cmd_set_return_ok
cmd_set_3_is_clear:
		bcf SENSOR_3_PORT, SENSOR_3_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_4_PRESENT
cmd_set_sensor_4:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_4_TYPE)
		btfss packet6, 0
		goto cmd_set_4_is_clear
		bsf SENSOR_4_PORT, SENSOR_4_PIN
		goto cmd_set_return_ok
cmd_set_4_is_clear:
		bcf SENSOR_4_PORT, SENSOR_4_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_5_PRESENT
cmd_set_sensor_5:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_5_TYPE)
		btfss packet6, 0
		goto cmd_set_5_is_clear
		bsf SENSOR_5_PORT, SENSOR_5_PIN
		goto cmd_set_return_ok
cmd_set_5_is_clear:
		bcf SENSOR_5_PORT, SENSOR_5_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_6_PRESENT
cmd_set_sensor_6:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_6_TYPE)
		btfss packet6, 0
		goto cmd_set_6_is_clear
		bsf SENSOR_6_PORT, SENSOR_6_PIN
		goto cmd_set_return_ok
cmd_set_6_is_clear:
		bcf SENSOR_6_PORT, SENSOR_6_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_7_PRESENT
cmd_set_sensor_7:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_7_TYPE)
		btfss packet6, 0
		goto cmd_set_7_is_clear
		bsf SENSOR_7_PORT, SENSOR_7_PIN
		goto cmd_set_return_ok
cmd_set_7_is_clear:
		bcf SENSOR_7_PORT, SENSOR_7_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_8_PRESENT
cmd_set_sensor_8:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_8_TYPE)
		btfss packet6, 0
		goto cmd_set_8_is_clear
		bsf SENSOR_8_PORT, SENSOR_8_PIN
		goto cmd_set_return_ok
cmd_set_8_is_clear:
		bcf SENSOR_8_PORT, SENSOR_8_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_9_PRESENT
cmd_set_sensor_9:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_9_TYPE)
		btfss packet6, 0
		goto cmd_set_9_is_clear
		bsf SENSOR_9_PORT, SENSOR_9_PIN
		goto cmd_set_return_ok
cmd_set_9_is_clear:
		bcf SENSOR_9_PORT, SENSOR_9_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_10_PRESENT
cmd_set_sensor_10:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_10_TYPE)
		btfss packet6, 0
		goto cmd_set_10_is_clear
		bsf SENSOR_10_PORT, SENSOR_10_PIN
		goto cmd_set_return_ok
cmd_set_10_is_clear:
		bcf SENSOR_10_PORT, SENSOR_10_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_11_PRESENT
cmd_set_sensor_11:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_11_TYPE)
		btfss packet6, 0
		goto cmd_set_11_is_clear
		bsf SENSOR_11_PORT, SENSOR_11_PIN
		goto cmd_set_return_ok
cmd_set_11_is_clear:
		bcf SENSOR_11_PORT, SENSOR_11_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_12_PRESENT
cmd_set_sensor_12:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_12_TYPE)
		btfss packet6, 0
		goto cmd_set_12_is_clear
		bsf SENSOR_12_PORT, SENSOR_12_PIN
		goto cmd_set_return_ok
cmd_set_12_is_clear:
		bcf SENSOR_12_PORT, SENSOR_12_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_13_PRESENT
cmd_set_sensor_13:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_13_TYPE)
		btfss packet6, 0
		goto cmd_set_13_is_clear
		bsf SENSOR_13_PORT, SENSOR_13_PIN
		goto cmd_set_return_ok
cmd_set_13_is_clear:
		bcf SENSOR_13_PORT, SENSOR_13_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_14_PRESENT
cmd_set_sensor_14:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_14_TYPE)
		btfss packet6, 0
		goto cmd_set_14_is_clear
		bsf SENSOR_14_PORT, SENSOR_14_PIN
		goto cmd_set_return_ok
cmd_set_14_is_clear:
		bcf SENSOR_14_PORT, SENSOR_14_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_15_PRESENT
cmd_set_sensor_15:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_15_TYPE)
		btfss packet6, 0
		goto cmd_set_15_is_clear
		bsf SENSOR_15_PORT, SENSOR_15_PIN
		goto cmd_set_return_ok
cmd_set_15_is_clear:
		bcf SENSOR_15_PORT, SENSOR_15_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_16_PRESENT
cmd_set_sensor_16:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_16_TYPE)
		btfss packet6, 0
		goto cmd_set_16_is_clear
		bsf SENSOR_16_PORT, SENSOR_16_PIN
		goto cmd_set_return_ok
cmd_set_16_is_clear:
		bcf SENSOR_16_PORT, SENSOR_16_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_17_PRESENT
cmd_set_sensor_17:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_17_TYPE)
		btfss packet6, 0
		goto cmd_set_17_is_clear
		bsf SENSOR_17_PORT, SENSOR_17_PIN
		goto cmd_set_return_ok
cmd_set_17_is_clear:
		bcf SENSOR_17_PORT, SENSOR_17_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_18_PRESENT
cmd_set_sensor_18:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_18_TYPE)
		btfss packet6, 0
		goto cmd_set_18_is_clear
		bsf SENSOR_18_PORT, SENSOR_18_PIN
		goto cmd_set_return_ok
cmd_set_18_is_clear:
		bcf SENSOR_18_PORT, SENSOR_18_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_19_PRESENT
cmd_set_sensor_19:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_19_TYPE)
		btfss packet6, 0
		goto cmd_set_19_is_clear
		bsf SENSOR_19_PORT, SENSOR_19_PIN
		goto cmd_set_return_ok
cmd_set_19_is_clear:
		bcf SENSOR_19_PORT, SENSOR_19_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_20_PRESENT
cmd_set_sensor_20:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_20_TYPE)
		btfss packet6, 0
		goto cmd_set_20_is_clear
		bsf SENSOR_20_PORT, SENSOR_20_PIN
		goto cmd_set_return_ok
cmd_set_20_is_clear:
		bcf SENSOR_20_PORT, SENSOR_20_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_21_PRESENT
cmd_set_sensor_21:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_21_TYPE)
		btfss packet6, 0
		goto cmd_set_21_is_clear
		bsf SENSOR_21_PORT, SENSOR_21_PIN
		goto cmd_set_return_ok
cmd_set_21_is_clear:
		bcf SENSOR_21_PORT, SENSOR_21_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_22_PRESENT
cmd_set_sensor_22:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_22_TYPE)
		btfss packet6, 0
		goto cmd_set_22_is_clear
		bsf SENSOR_22_PORT, SENSOR_22_PIN
		goto cmd_set_return_ok
cmd_set_22_is_clear:
		bcf SENSOR_22_PORT, SENSOR_22_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_23_PRESENT
cmd_set_sensor_23:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_23_TYPE)
		btfss packet6, 0
		goto cmd_set_23_is_clear
		bsf SENSOR_23_PORT, SENSOR_23_PIN
		goto cmd_set_return_ok
cmd_set_23_is_clear:
		bcf SENSOR_23_PORT, SENSOR_23_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_24_PRESENT
cmd_set_sensor_24:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_24_TYPE)
		btfss packet6, 0
		goto cmd_set_24_is_clear
		bsf SENSOR_24_PORT, SENSOR_24_PIN
		goto cmd_set_return_ok
cmd_set_24_is_clear:
		bcf SENSOR_24_PORT, SENSOR_24_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_25_PRESENT
cmd_set_sensor_25:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_25_TYPE)
		btfss packet6, 0
		goto cmd_set_25_is_clear
		bsf SENSOR_25_PORT, SENSOR_25_PIN
		goto cmd_set_return_ok
cmd_set_25_is_clear:
		bcf SENSOR_25_PORT, SENSOR_25_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_26_PRESENT
cmd_set_sensor_26:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_26_TYPE)
		btfss packet6, 0
		goto cmd_set_26_is_clear
		bsf SENSOR_26_PORT, SENSOR_26_PIN
		goto cmd_set_return_ok
cmd_set_26_is_clear:
		bcf SENSOR_26_PORT, SENSOR_26_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_27_PRESENT
cmd_set_sensor_27:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_27_TYPE)
		btfss packet6, 0
		goto cmd_set_27_is_clear
		bsf SENSOR_27_PORT, SENSOR_27_PIN
		goto cmd_set_return_ok
cmd_set_27_is_clear:
		bcf SENSOR_27_PORT, SENSOR_27_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_28_PRESENT
cmd_set_sensor_28:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_28_TYPE)
		btfss packet6, 0
		goto cmd_set_28_is_clear
		bsf SENSOR_28_PORT, SENSOR_28_PIN
		goto cmd_set_return_ok
cmd_set_28_is_clear:
		bcf SENSOR_28_PORT, SENSOR_28_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_29_PRESENT
cmd_set_sensor_29:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_29_TYPE)
		btfss packet6, 0
		goto cmd_set_29_is_clear
		bsf SENSOR_29_PORT, SENSOR_29_PIN
		goto cmd_set_return_ok
cmd_set_29_is_clear:
		bcf SENSOR_29_PORT, SENSOR_29_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_30_PRESENT
cmd_set_sensor_30:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_30_TYPE)
		btfss packet6, 0
		goto cmd_set_30_is_clear
		bsf SENSOR_30_PORT, SENSOR_30_PIN
		goto cmd_set_return_ok
cmd_set_30_is_clear:
		bcf SENSOR_30_PORT, SENSOR_30_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_31_PRESENT
cmd_set_sensor_31:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_31_TYPE)
		btfss packet6, 0
		goto cmd_set_31_is_clear
		bsf SENSOR_31_PORT, SENSOR_31_PIN
		goto cmd_set_return_ok
cmd_set_31_is_clear:
		bcf SENSOR_31_PORT, SENSOR_31_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_32_PRESENT
cmd_set_sensor_32:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_32_TYPE)
		btfss packet6, 0
		goto cmd_set_32_is_clear
		bsf SENSOR_32_PORT, SENSOR_32_PIN
		goto cmd_set_return_ok
cmd_set_32_is_clear:
		bcf SENSOR_32_PORT, SENSOR_32_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_33_PRESENT
cmd_set_sensor_33:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_33_TYPE)
		btfss packet6, 0
		goto cmd_set_33_is_clear
		bsf SENSOR_33_PORT, SENSOR_33_PIN
		goto cmd_set_return_ok
cmd_set_33_is_clear:
		bcf SENSOR_33_PORT, SENSOR_33_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_34_PRESENT
cmd_set_sensor_34:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_34_TYPE)
		btfss packet6, 0
		goto cmd_set_34_is_clear
		bsf SENSOR_34_PORT, SENSOR_34_PIN
		goto cmd_set_return_ok
cmd_set_34_is_clear:
		bcf SENSOR_34_PORT, SENSOR_34_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_35_PRESENT
cmd_set_sensor_35:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_35_TYPE)
		btfss packet6, 0
		goto cmd_set_35_is_clear
		bsf SENSOR_35_PORT, SENSOR_35_PIN
		goto cmd_set_return_ok
cmd_set_35_is_clear:
		bcf SENSOR_35_PORT, SENSOR_35_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_36_PRESENT
cmd_set_sensor_36:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_36_TYPE)
		btfss packet6, 0
		goto cmd_set_36_is_clear
		bsf SENSOR_36_PORT, SENSOR_36_PIN
		goto cmd_set_return_ok
cmd_set_36_is_clear:
		bcf SENSOR_36_PORT, SENSOR_36_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_37_PRESENT
cmd_set_sensor_37:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_37_TYPE)
		btfss packet6, 0
		goto cmd_set_37_is_clear
		bsf SENSOR_37_PORT, SENSOR_37_PIN
		goto cmd_set_return_ok
cmd_set_37_is_clear:
		bcf SENSOR_37_PORT, SENSOR_37_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_38_PRESENT
cmd_set_sensor_38:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_38_TYPE)
		btfss packet6, 0
		goto cmd_set_38_is_clear
		bsf SENSOR_38_PORT, SENSOR_38_PIN
		goto cmd_set_return_ok
cmd_set_38_is_clear:
		bcf SENSOR_38_PORT, SENSOR_38_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_39_PRESENT
cmd_set_sensor_39:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_39_TYPE)
		btfss packet6, 0
		goto cmd_set_39_is_clear
		bsf SENSOR_39_PORT, SENSOR_39_PIN
		goto cmd_set_return_ok
cmd_set_39_is_clear:
		bcf SENSOR_39_PORT, SENSOR_39_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_40_PRESENT
cmd_set_sensor_40:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_40_TYPE)
		btfss packet6, 0
		goto cmd_set_40_is_clear
		bsf SENSOR_40_PORT, SENSOR_40_PIN
		goto cmd_set_return_ok
cmd_set_40_is_clear:
		bcf SENSOR_40_PORT, SENSOR_40_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_41_PRESENT
cmd_set_sensor_41:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_41_TYPE)
		btfss packet6, 0
		goto cmd_set_41_is_clear
		bsf SENSOR_41_PORT, SENSOR_41_PIN
		goto cmd_set_return_ok
cmd_set_41_is_clear:
		bcf SENSOR_41_PORT, SENSOR_41_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_42_PRESENT
cmd_set_sensor_42:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_42_TYPE)
		btfss packet6, 0
		goto cmd_set_42_is_clear
		bsf SENSOR_42_PORT, SENSOR_42_PIN
		goto cmd_set_return_ok
cmd_set_42_is_clear:
		bcf SENSOR_42_PORT, SENSOR_42_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_43_PRESENT
cmd_set_sensor_43:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_43_TYPE)
		btfss packet6, 0
		goto cmd_set_43_is_clear
		bsf SENSOR_43_PORT, SENSOR_43_PIN
		goto cmd_set_return_ok
cmd_set_43_is_clear:
		bcf SENSOR_43_PORT, SENSOR_43_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_44_PRESENT
cmd_set_sensor_44:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_44_TYPE)
		btfss packet6, 0
		goto cmd_set_44_is_clear
		bsf SENSOR_44_PORT, SENSOR_44_PIN
		goto cmd_set_return_ok
cmd_set_44_is_clear:
		bcf SENSOR_44_PORT, SENSOR_44_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_45_PRESENT
cmd_set_sensor_45:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_45_TYPE)
		btfss packet6, 0
		goto cmd_set_45_is_clear
		bsf SENSOR_45_PORT, SENSOR_45_PIN
		goto cmd_set_return_ok
cmd_set_45_is_clear:
		bcf SENSOR_45_PORT, SENSOR_45_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_46_PRESENT
cmd_set_sensor_46:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_46_TYPE)
		btfss packet6, 0
		goto cmd_set_46_is_clear
		bsf SENSOR_46_PORT, SENSOR_46_PIN
		goto cmd_set_return_ok
cmd_set_46_is_clear:
		bcf SENSOR_46_PORT, SENSOR_46_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_47_PRESENT
cmd_set_sensor_47:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_47_TYPE)
		btfss packet6, 0
		goto cmd_set_47_is_clear
		bsf SENSOR_47_PORT, SENSOR_47_PIN
		goto cmd_set_return_ok
cmd_set_47_is_clear:
		bcf SENSOR_47_PORT, SENSOR_47_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_48_PRESENT
cmd_set_sensor_48:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_48_TYPE)
		btfss packet6, 0
		goto cmd_set_48_is_clear
		bsf SENSOR_48_PORT, SENSOR_48_PIN
		goto cmd_set_return_ok
cmd_set_48_is_clear:
		bcf SENSOR_48_PORT, SENSOR_48_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_49_PRESENT
cmd_set_sensor_49:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_49_TYPE)
		btfss packet6, 0
		goto cmd_set_49_is_clear
		bsf SENSOR_49_PORT, SENSOR_49_PIN
		goto cmd_set_return_ok
cmd_set_49_is_clear:
		bcf SENSOR_49_PORT, SENSOR_49_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_50_PRESENT
cmd_set_sensor_50:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_50_TYPE)
		btfss packet6, 0
		goto cmd_set_50_is_clear
		bsf SENSOR_50_PORT, SENSOR_50_PIN
		goto cmd_set_return_ok
cmd_set_50_is_clear:
		bcf SENSOR_50_PORT, SENSOR_50_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_51_PRESENT
cmd_set_sensor_51:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_51_TYPE)
		btfss packet6, 0
		goto cmd_set_51_is_clear
		bsf SENSOR_51_PORT, SENSOR_51_PIN
		goto cmd_set_return_ok
cmd_set_51_is_clear:
		bcf SENSOR_51_PORT, SENSOR_51_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_52_PRESENT
cmd_set_sensor_52:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_52_TYPE)
		btfss packet6, 0
		goto cmd_set_52_is_clear
		bsf SENSOR_52_PORT, SENSOR_52_PIN
		goto cmd_set_return_ok
cmd_set_52_is_clear:
		bcf SENSOR_52_PORT, SENSOR_52_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_53_PRESENT
cmd_set_sensor_53:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_53_TYPE)
		btfss packet6, 0
		goto cmd_set_53_is_clear
		bsf SENSOR_53_PORT, SENSOR_53_PIN
		goto cmd_set_return_ok
cmd_set_53_is_clear:
		bcf SENSOR_53_PORT, SENSOR_53_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_54_PRESENT
cmd_set_sensor_54:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_54_TYPE)
		btfss packet6, 0
		goto cmd_set_54_is_clear
		bsf SENSOR_54_PORT, SENSOR_54_PIN
		goto cmd_set_return_ok
cmd_set_54_is_clear:
		bcf SENSOR_54_PORT, SENSOR_54_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_55_PRESENT
cmd_set_sensor_55:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_55_TYPE)
		btfss packet6, 0
		goto cmd_set_55_is_clear
		bsf SENSOR_55_PORT, SENSOR_55_PIN
		goto cmd_set_return_ok
cmd_set_55_is_clear:
		bcf SENSOR_55_PORT, SENSOR_55_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_56_PRESENT
cmd_set_sensor_56:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_56_TYPE)
		btfss packet6, 0
		goto cmd_set_56_is_clear
		bsf SENSOR_56_PORT, SENSOR_56_PIN
		goto cmd_set_return_ok
cmd_set_56_is_clear:
		bcf SENSOR_56_PORT, SENSOR_56_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_57_PRESENT
cmd_set_sensor_57:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_57_TYPE)
		btfss packet6, 0
		goto cmd_set_57_is_clear
		bsf SENSOR_57_PORT, SENSOR_57_PIN
		goto cmd_set_return_ok
cmd_set_57_is_clear:
		bcf SENSOR_57_PORT, SENSOR_57_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_58_PRESENT
cmd_set_sensor_58:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_58_TYPE)
		btfss packet6, 0
		goto cmd_set_58_is_clear
		bsf SENSOR_58_PORT, SENSOR_58_PIN
		goto cmd_set_return_ok
cmd_set_58_is_clear:
		bcf SENSOR_58_PORT, SENSOR_58_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_59_PRESENT
cmd_set_sensor_59:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_59_TYPE)
		btfss packet6, 0
		goto cmd_set_59_is_clear
		bsf SENSOR_59_PORT, SENSOR_59_PIN
		goto cmd_set_return_ok
cmd_set_59_is_clear:
		bcf SENSOR_59_PORT, SENSOR_59_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_60_PRESENT
cmd_set_sensor_60:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_60_TYPE)
		btfss packet6, 0
		goto cmd_set_60_is_clear
		bsf SENSOR_60_PORT, SENSOR_60_PIN
		goto cmd_set_return_ok
cmd_set_60_is_clear:
		bcf SENSOR_60_PORT, SENSOR_60_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_61_PRESENT
cmd_set_sensor_61:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_61_TYPE)
		btfss packet6, 0
		goto cmd_set_61_is_clear
		bsf SENSOR_61_PORT, SENSOR_61_PIN
		goto cmd_set_return_ok
cmd_set_61_is_clear:
		bcf SENSOR_61_PORT, SENSOR_61_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_62_PRESENT
cmd_set_sensor_62:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_62_TYPE)
		btfss packet6, 0
		goto cmd_set_62_is_clear
		bsf SENSOR_62_PORT, SENSOR_62_PIN
		goto cmd_set_return_ok
cmd_set_62_is_clear:
		bcf SENSOR_62_PORT, SENSOR_62_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_63_PRESENT
cmd_set_sensor_63:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_63_TYPE)
		btfss packet6, 0
		goto cmd_set_63_is_clear
		bsf SENSOR_63_PORT, SENSOR_63_PIN
		goto cmd_set_return_ok
cmd_set_63_is_clear:
		bcf SENSOR_63_PORT, SENSOR_63_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_64_PRESENT
cmd_set_sensor_64:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_64_TYPE)
		btfss packet6, 0
		goto cmd_set_64_is_clear
		bsf SENSOR_64_PORT, SENSOR_64_PIN
		goto cmd_set_return_ok
cmd_set_64_is_clear:
		bcf SENSOR_64_PORT, SENSOR_64_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_65_PRESENT
cmd_set_sensor_65:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_65_TYPE)
		btfss packet6, 0
		goto cmd_set_65_is_clear
		bsf SENSOR_65_PORT, SENSOR_65_PIN
		goto cmd_set_return_ok
cmd_set_65_is_clear:
		bcf SENSOR_65_PORT, SENSOR_65_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_66_PRESENT
cmd_set_sensor_66:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_66_TYPE)
		btfss packet6, 0
		goto cmd_set_66_is_clear
		bsf SENSOR_66_PORT, SENSOR_66_PIN
		goto cmd_set_return_ok
cmd_set_66_is_clear:
		bcf SENSOR_66_PORT, SENSOR_66_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_67_PRESENT
cmd_set_sensor_67:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_67_TYPE)
		btfss packet6, 0
		goto cmd_set_67_is_clear
		bsf SENSOR_67_PORT, SENSOR_67_PIN
		goto cmd_set_return_ok
cmd_set_67_is_clear:
		bcf SENSOR_67_PORT, SENSOR_67_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_68_PRESENT
cmd_set_sensor_68:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_68_TYPE)
		btfss packet6, 0
		goto cmd_set_68_is_clear
		bsf SENSOR_68_PORT, SENSOR_68_PIN
		goto cmd_set_return_ok
cmd_set_68_is_clear:
		bcf SENSOR_68_PORT, SENSOR_68_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_69_PRESENT
cmd_set_sensor_69:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_69_TYPE)
		btfss packet6, 0
		goto cmd_set_69_is_clear
		bsf SENSOR_69_PORT, SENSOR_69_PIN
		goto cmd_set_return_ok
cmd_set_69_is_clear:
		bcf SENSOR_69_PORT, SENSOR_69_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_70_PRESENT
cmd_set_sensor_70:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_70_TYPE)
		btfss packet6, 0
		goto cmd_set_70_is_clear
		bsf SENSOR_70_PORT, SENSOR_70_PIN
		goto cmd_set_return_ok
cmd_set_70_is_clear:
		bcf SENSOR_70_PORT, SENSOR_70_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_71_PRESENT
cmd_set_sensor_71:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_71_TYPE)
		btfss packet6, 0
		goto cmd_set_71_is_clear
		bsf SENSOR_71_PORT, SENSOR_71_PIN
		goto cmd_set_return_ok
cmd_set_71_is_clear:
		bcf SENSOR_71_PORT, SENSOR_71_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_72_PRESENT
cmd_set_sensor_72:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_72_TYPE)
		btfss packet6, 0
		goto cmd_set_72_is_clear
		bsf SENSOR_72_PORT, SENSOR_72_PIN
		goto cmd_set_return_ok
cmd_set_72_is_clear:
		bcf SENSOR_72_PORT, SENSOR_72_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_73_PRESENT
cmd_set_sensor_73:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_73_TYPE)
		btfss packet6, 0
		goto cmd_set_73_is_clear
		bsf SENSOR_73_PORT, SENSOR_73_PIN
		goto cmd_set_return_ok
cmd_set_73_is_clear:
		bcf SENSOR_73_PORT, SENSOR_73_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_74_PRESENT
cmd_set_sensor_74:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_74_TYPE)
		btfss packet6, 0
		goto cmd_set_74_is_clear
		bsf SENSOR_74_PORT, SENSOR_74_PIN
		goto cmd_set_return_ok
cmd_set_74_is_clear:
		bcf SENSOR_74_PORT, SENSOR_74_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_75_PRESENT
cmd_set_sensor_75:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_75_TYPE)
		btfss packet6, 0
		goto cmd_set_75_is_clear
		bsf SENSOR_75_PORT, SENSOR_75_PIN
		goto cmd_set_return_ok
cmd_set_75_is_clear:
		bcf SENSOR_75_PORT, SENSOR_75_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_76_PRESENT
cmd_set_sensor_76:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_76_TYPE)
		btfss packet6, 0
		goto cmd_set_76_is_clear
		bsf SENSOR_76_PORT, SENSOR_76_PIN
		goto cmd_set_return_ok
cmd_set_76_is_clear:
		bcf SENSOR_76_PORT, SENSOR_76_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_77_PRESENT
cmd_set_sensor_77:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_77_TYPE)
		btfss packet6, 0
		goto cmd_set_77_is_clear
		bsf SENSOR_77_PORT, SENSOR_77_PIN
		goto cmd_set_return_ok
cmd_set_77_is_clear:
		bcf SENSOR_77_PORT, SENSOR_77_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_78_PRESENT
cmd_set_sensor_78:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_78_TYPE)
		btfss packet6, 0
		goto cmd_set_78_is_clear
		bsf SENSOR_78_PORT, SENSOR_78_PIN
		goto cmd_set_return_ok
cmd_set_78_is_clear:
		bcf SENSOR_78_PORT, SENSOR_78_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_79_PRESENT
cmd_set_sensor_79:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_79_TYPE)
		btfss packet6, 0
		goto cmd_set_79_is_clear
		bsf SENSOR_79_PORT, SENSOR_79_PIN
		goto cmd_set_return_ok
cmd_set_79_is_clear:
		bcf SENSOR_79_PORT, SENSOR_79_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_80_PRESENT
cmd_set_sensor_80:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_80_TYPE)
		btfss packet6, 0
		goto cmd_set_80_is_clear
		bsf SENSOR_80_PORT, SENSOR_80_PIN
		goto cmd_set_return_ok
cmd_set_80_is_clear:
		bcf SENSOR_80_PORT, SENSOR_80_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_81_PRESENT
cmd_set_sensor_81:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_81_TYPE)
		btfss packet6, 0
		goto cmd_set_81_is_clear
		bsf SENSOR_81_PORT, SENSOR_81_PIN
		goto cmd_set_return_ok
cmd_set_81_is_clear:
		bcf SENSOR_81_PORT, SENSOR_81_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_82_PRESENT
cmd_set_sensor_82:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_82_TYPE)
		btfss packet6, 0
		goto cmd_set_82_is_clear
		bsf SENSOR_82_PORT, SENSOR_82_PIN
		goto cmd_set_return_ok
cmd_set_82_is_clear:
		bcf SENSOR_82_PORT, SENSOR_82_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_83_PRESENT
cmd_set_sensor_83:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_83_TYPE)
		btfss packet6, 0
		goto cmd_set_83_is_clear
		bsf SENSOR_83_PORT, SENSOR_83_PIN
		goto cmd_set_return_ok
cmd_set_83_is_clear:
		bcf SENSOR_83_PORT, SENSOR_83_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_84_PRESENT
cmd_set_sensor_84:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_84_TYPE)
		btfss packet6, 0
		goto cmd_set_84_is_clear
		bsf SENSOR_84_PORT, SENSOR_84_PIN
		goto cmd_set_return_ok
cmd_set_84_is_clear:
		bcf SENSOR_84_PORT, SENSOR_84_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_85_PRESENT
cmd_set_sensor_85:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_85_TYPE)
		btfss packet6, 0
		goto cmd_set_85_is_clear
		bsf SENSOR_85_PORT, SENSOR_85_PIN
		goto cmd_set_return_ok
cmd_set_85_is_clear:
		bcf SENSOR_85_PORT, SENSOR_85_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_86_PRESENT
cmd_set_sensor_86:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_86_TYPE)
		btfss packet6, 0
		goto cmd_set_86_is_clear
		bsf SENSOR_86_PORT, SENSOR_86_PIN
		goto cmd_set_return_ok
cmd_set_86_is_clear:
		bcf SENSOR_86_PORT, SENSOR_86_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_87_PRESENT
cmd_set_sensor_87:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_87_TYPE)
		btfss packet6, 0
		goto cmd_set_87_is_clear
		bsf SENSOR_87_PORT, SENSOR_87_PIN
		goto cmd_set_return_ok
cmd_set_87_is_clear:
		bcf SENSOR_87_PORT, SENSOR_87_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_88_PRESENT
cmd_set_sensor_88:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_88_TYPE)
		btfss packet6, 0
		goto cmd_set_88_is_clear
		bsf SENSOR_88_PORT, SENSOR_88_PIN
		goto cmd_set_return_ok
cmd_set_88_is_clear:
		bcf SENSOR_88_PORT, SENSOR_88_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_89_PRESENT
cmd_set_sensor_89:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_89_TYPE)
		btfss packet6, 0
		goto cmd_set_89_is_clear
		bsf SENSOR_89_PORT, SENSOR_89_PIN
		goto cmd_set_return_ok
cmd_set_89_is_clear:
		bcf SENSOR_89_PORT, SENSOR_89_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_90_PRESENT
cmd_set_sensor_90:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_90_TYPE)
		btfss packet6, 0
		goto cmd_set_90_is_clear
		bsf SENSOR_90_PORT, SENSOR_90_PIN
		goto cmd_set_return_ok
cmd_set_90_is_clear:
		bcf SENSOR_90_PORT, SENSOR_90_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_91_PRESENT
cmd_set_sensor_91:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_91_TYPE)
		btfss packet6, 0
		goto cmd_set_91_is_clear
		bsf SENSOR_91_PORT, SENSOR_91_PIN
		goto cmd_set_return_ok
cmd_set_91_is_clear:
		bcf SENSOR_91_PORT, SENSOR_91_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_92_PRESENT
cmd_set_sensor_92:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_92_TYPE)
		btfss packet6, 0
		goto cmd_set_92_is_clear
		bsf SENSOR_92_PORT, SENSOR_92_PIN
		goto cmd_set_return_ok
cmd_set_92_is_clear:
		bcf SENSOR_92_PORT, SENSOR_92_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_93_PRESENT
cmd_set_sensor_93:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_93_TYPE)
		btfss packet6, 0
		goto cmd_set_93_is_clear
		bsf SENSOR_93_PORT, SENSOR_93_PIN
		goto cmd_set_return_ok
cmd_set_93_is_clear:
		bcf SENSOR_93_PORT, SENSOR_93_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_94_PRESENT
cmd_set_sensor_94:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_94_TYPE)
		btfss packet6, 0
		goto cmd_set_94_is_clear
		bsf SENSOR_94_PORT, SENSOR_94_PIN
		goto cmd_set_return_ok
cmd_set_94_is_clear:
		bcf SENSOR_94_PORT, SENSOR_94_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_95_PRESENT
cmd_set_sensor_95:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_95_TYPE)
		btfss packet6, 0
		goto cmd_set_95_is_clear
		bsf SENSOR_95_PORT, SENSOR_95_PIN
		goto cmd_set_return_ok
cmd_set_95_is_clear:
		bcf SENSOR_95_PORT, SENSOR_95_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_96_PRESENT
cmd_set_sensor_96:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_96_TYPE)
		btfss packet6, 0
		goto cmd_set_96_is_clear
		bsf SENSOR_96_PORT, SENSOR_96_PIN
		goto cmd_set_return_ok
cmd_set_96_is_clear:
		bcf SENSOR_96_PORT, SENSOR_96_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_97_PRESENT
cmd_set_sensor_97:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_97_TYPE)
		btfss packet6, 0
		goto cmd_set_97_is_clear
		bsf SENSOR_97_PORT, SENSOR_97_PIN
		goto cmd_set_return_ok
cmd_set_97_is_clear:
		bcf SENSOR_97_PORT, SENSOR_97_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_98_PRESENT
cmd_set_sensor_98:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_98_TYPE)
		btfss packet6, 0
		goto cmd_set_98_is_clear
		bsf SENSOR_98_PORT, SENSOR_98_PIN
		goto cmd_set_return_ok
cmd_set_98_is_clear:
		bcf SENSOR_98_PORT, SENSOR_98_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
#ifdef SENSOR_99_PRESENT
cmd_set_sensor_99:
	#if (SENSOR_ID_GENERIC_DIGITAL_OUT == SENSOR_99_TYPE)
		btfss packet6, 0
		goto cmd_set_99_is_clear
		bsf SENSOR_99_PORT, SENSOR_99_PIN
		goto cmd_set_return_ok
cmd_set_99_is_clear:
		bcf SENSOR_99_PORT, SENSOR_99_PIN
		goto cmd_set_return_ok
	#else
		goto cmd_set_return_wrong_type
	#endif
#endif
cmd_set_return_wrong_type:

	clrf packet4
	clrf packet5
	clrf packet6
	movlw ERR_SET_SENSOR_NODE_WRONG_TYPE
	movwf packet7
	return

cmd_set_return_ok:
	clrf packet4
	clrf packet5
	clrf packet6
	movlw ERR_SET_SENSOR_NONE
	movwf packet7
	return

	end