	EXTERN debugger_init
	EXTERN debugger_spitvalue


#define DEBUGGER_INITTED 				0x01
#define DEBUGGER_AWAITING_FIRST_PACKET 	0x02
#define DEBUGGER_GOT_BYTE				0x03
#define DEBUGGER_GOT_ALIGNMENT_BYTE		0x04
#define DEBUGGER_GOT_ALIGNMENT_PACKET	0x05
#define DEBUGGER_GOT_CMD				0x06
#define DEBUGGER_GOT_MY_CMD				0x07
#define DEBUGGER_GOT_CMD_PING			0x08
#define DEBUGGER_GOT_CMD_GETSENSOR		0x09
#define DEBUGGER_GOT_CMD_SETSENSOR		0x0A
#define DEBUGGER_GOT_WRONG_P			0x0B
#define DEBUGGER_UNKNOWN_SENSOR			0x0C
#define DEBUGGER_SET_3					0x0D
#define DEBUGGER_RX_OVERFLOW			0x0E

